services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 4740201_semprenacasa
      MYSQL_USER: 4740201_semprenacasa
      MYSQL_PASSWORD: SempreNaCasa_2026
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: 4740201_semprenacasa
      PMA_PASSWORD: SempreNaCasa_2026

volumes:
  db_data: