let medicion_def_tests = Array(
    ['medicion', 'valor_registrado', 'input', 1, 'cumple tamaño minimo', 'ADD', 'valor_registrado_min_size_KO'],
    ['medicion', 'valor_registrado', 'input', 2, 'cumple tamaño maximo', 'ADD', 'valor_registrado_max_size_KO'],
    ['medicion', 'valor_registrado', 'input', 3, 'cumple formato', 'ADD', 'valor_registrado_format_KO'],
    ['medicion', 'valor_registrado', 'input', 4, 'es correcto', 'ADD', true],
    ['medicion', 'valor_registrado', 'input', 5, 'cumple tamaño minimo', 'EDIT', 'valor_registrado_min_size_KO'],
    ['medicion', 'valor_registrado', 'input', 6, 'cumple tamaño maximo', 'EDIT', 'valor_registrado_max_size_KO'],
    ['medicion', 'valor_registrado', 'input', 7, 'cumple formato', 'EDIT', 'valor_registrado_format_KO'],
    ['medicion', 'valor_registrado', 'input', 8, 'es correcto', 'EDIT', true],
    ['medicion', 'fecha_medicion', 'input', 9, 'cumple formato', 'ADD', 'fecha_medicion_format_KO'],
    ['medicion', 'fecha_medicion', 'input', 10, 'es correcto', 'ADD', true],
    ['medicion', 'fecha_medicion', 'input', 11, 'cumple formato', 'EDIT', 'fecha_medicion_format_KO'],
    ['medicion', 'fecha_medicion', 'input', 12, 'es correcto', 'EDIT', true],
    ['medicion', 'valor_registrado', 'input', 349, 'es correcto vacío', 'SEARCH', true],
    ['medicion', 'fecha_medicion', 'input', 350, 'es correcto vacío', 'SEARCH', true],
    ['medicion', 'valor_registrado', 'input', 402, 'es correcto como substring', 'SEARCH', true],
    ['medicion', 'valor_registrado', 'input', 409, 'cumple tamaño maximo', 'SEARCH', 'valor_registrado_max_size_KO'],
    ['medicion', 'valor_registrado', 'input', 410, 'cumple formato', 'SEARCH', 'valor_registrado_format_KO'],
    ['medicion', 'fecha_medicion', 'input', 411, 'cumple tamaño maximo', 'SEARCH', 'fecha_medicion_max_size_KO'],
    ['medicion', 'fecha_medicion', 'input', 412, 'cumple formato', 'SEARCH', 'fecha_medicion_format_KO'],
    // 'archivo_adjunto' ya no es un input de fichero en medicion.js (el formulario actual
    // reutiliza ese atributo de la BD para un textarea de texto libre 'observaciones', ver
    // Entidad_Abstracta/medicion.js). Las pruebas 13-26 y 351 de fichero se han sustituido
    // por pruebas reales de 'observaciones' (comprobar_observaciones / *_observaciones_validation).
    ['medicion', 'observaciones', 'input', 468, 'es correcto vacío', 'ADD', true],
    ['medicion', 'observaciones', 'input', 469, 'es correcto', 'ADD', true],
    ['medicion', 'observaciones', 'input', 470, 'cumple tamaño maximo', 'ADD', 'observaciones_max_size_KO'],
    ['medicion', 'observaciones', 'input', 471, 'cumple formato', 'ADD', 'observaciones_format_KO'],
    ['medicion', 'observaciones', 'input', 472, 'es correcto vacío', 'EDIT', true],
    ['medicion', 'observaciones', 'input', 473, 'cumple tamaño maximo', 'EDIT', 'observaciones_max_size_KO'],
    ['medicion', 'observaciones', 'input', 474, 'cumple formato', 'EDIT', 'observaciones_format_KO'],
    ['medicion', 'observaciones', 'input', 475, 'es correcto vacío', 'SEARCH', true],
    ['medicion', 'observaciones', 'input', 476, 'cumple tamaño maximo', 'SEARCH', 'observaciones_max_size_KO'],
    ['medicion', 'observaciones', 'input', 477, 'cumple formato', 'SEARCH', 'observaciones_format_KO']
);

let medicion_tests_fields = Array(
    ['medicion', 'valor_registrado', 1, 1, 'ADD', [{ valor_registrado: '' }], 'valor_registrado_min_size_KO'],
    ['medicion', 'valor_registrado', 2, 2, 'ADD', [{ valor_registrado: 'a'.repeat(51) }], 'valor_registrado_max_size_KO'],
    ['medicion', 'valor_registrado', 3, 3, 'ADD', [{ valor_registrado: '!!!' }], 'valor_registrado_format_KO'],
    ['medicion', 'valor_registrado', 4, 4, 'ADD', [{ valor_registrado: '25.5' }], true],
    ['medicion', 'valor_registrado', 5, 5, 'EDIT', [{ valor_registrado: '' }], 'valor_registrado_min_size_KO'],
    ['medicion', 'valor_registrado', 6, 6, 'EDIT', [{ valor_registrado: 'a'.repeat(51) }], 'valor_registrado_max_size_KO'],
    ['medicion', 'valor_registrado', 7, 7, 'EDIT', [{ valor_registrado: '!!!' }], 'valor_registrado_format_KO'],
    ['medicion', 'valor_registrado', 8, 8, 'EDIT', [{ valor_registrado: '25,5' }], true],
    ['medicion', 'fecha_medicion', 9, 9, 'ADD', [{ fecha_medicion: '32/14/2026' }], 'fecha_medicion_format_KO'],
    ['medicion', 'fecha_medicion', 10, 10, 'ADD', [{ fecha_medicion: '2026-03-26' }], true],
    ['medicion', 'fecha_medicion', 11, 11, 'EDIT', [{ fecha_medicion: '32/14/2026' }], 'fecha_medicion_format_KO'],
    ['medicion', 'fecha_medicion', 12, 12, 'EDIT', [{ fecha_medicion: '2026-03-26' }], true],
    ['medicion', 'valor_registrado', 349, 349, 'SEARCH', [{ valor_registrado: '' }], true],
    ['medicion', 'fecha_medicion', 350, 350, 'SEARCH', [{ fecha_medicion: '' }], true],
    ['medicion', 'valor_registrado', 402, 402, 'SEARCH', [{ valor_registrado: '25' }], true],
    ['medicion', 'valor_registrado', 409, 409, 'SEARCH', [{ valor_registrado: 'v'.repeat(51) }], 'valor_registrado_max_size_KO'],
    ['medicion', 'valor_registrado', 410, 410, 'SEARCH', [{ valor_registrado: '!!!' }], 'valor_registrado_format_KO'],
    ['medicion', 'fecha_medicion', 411, 411, 'SEARCH', [{ fecha_medicion: '1'.repeat(11) }], 'fecha_medicion_max_size_KO'],
    ['medicion', 'fecha_medicion', 412, 412, 'SEARCH', [{ fecha_medicion: 'abc/def' }], 'fecha_medicion_format_KO'],
    ['medicion', 'observaciones', 468, 468, 'ADD', [{ observaciones: '' }], true],
    ['medicion', 'observaciones', 469, 469, 'ADD', [{ observaciones: 'Todo correcto en la medición' }], true],
    ['medicion', 'observaciones', 470, 470, 'ADD', [{ observaciones: 'o'.repeat(501) }], 'observaciones_max_size_KO'],
    ['medicion', 'observaciones', 471, 471, 'ADD', [{ observaciones: '<script>' }], 'observaciones_format_KO'],
    ['medicion', 'observaciones', 472, 472, 'EDIT', [{ observaciones: '' }], true],
    ['medicion', 'observaciones', 473, 473, 'EDIT', [{ observaciones: 'o'.repeat(501) }], 'observaciones_max_size_KO'],
    ['medicion', 'observaciones', 474, 474, 'EDIT', [{ observaciones: '<script>' }], 'observaciones_format_KO'],
    ['medicion', 'observaciones', 475, 475, 'SEARCH', [{ observaciones: '' }], true],
    ['medicion', 'observaciones', 476, 476, 'SEARCH', [{ observaciones: 'o'.repeat(501) }], 'observaciones_max_size_KO'],
    ['medicion', 'observaciones', 477, 477, 'SEARCH', [{ observaciones: '<script>' }], 'observaciones_format_KO']
);

// medicion ya no tiene ningún campo de tipo fichero (ver nota sobre 'observaciones' arriba).
let medicion_tests_files = Array();

let opinion_def_tests = Array(
    ['opinion', 'fecha_opinion', 'input', 27, 'cumple formato', 'ADD', 'fecha_opinion_format_KO'],
    ['opinion', 'fecha_opinion', 'input', 28, 'es correcto', 'ADD', true],
    ['opinion', 'fecha_opinion', 'input', 29, 'cumple formato', 'EDIT', 'fecha_opinion_format_KO'],
    ['opinion', 'fecha_opinion', 'input', 30, 'es correcto', 'EDIT', true],
    ['opinion', 'conclusiones', 'input', 31, 'cumple tamaño minimo', 'ADD', 'conclusiones_min_size_KO'],
    ['opinion', 'conclusiones', 'input', 32, 'cumple tamaño maximo', 'ADD', 'conclusiones_max_size_KO'],
    ['opinion', 'conclusiones', 'input', 33, 'cumple formato', 'ADD', 'conclusiones_format_KO'],
    ['opinion', 'conclusiones', 'input', 34, 'es correcto', 'ADD', true],
    ['opinion', 'conclusiones', 'input', 35, 'cumple tamaño minimo', 'EDIT', 'conclusiones_min_size_KO'],
    ['opinion', 'conclusiones', 'input', 36, 'cumple tamaño maximo', 'EDIT', 'conclusiones_max_size_KO'],
    ['opinion', 'conclusiones', 'input', 37, 'cumple formato', 'EDIT', 'conclusiones_format_KO'],
    ['opinion', 'conclusiones', 'input', 38, 'es correcto', 'EDIT', true],
    ['opinion', 'fecha_opinion', 'input', 352, 'es correcto vacío', 'SEARCH', true],
    ['opinion', 'conclusiones', 'input', 353, 'es correcto vacío', 'SEARCH', true],
    ['opinion', 'conclusiones', 'input', 403, 'es correcto como substring', 'SEARCH', true],
    ['opinion', 'fecha_opinion', 'input', 413, 'cumple tamaño maximo', 'SEARCH', 'fecha_opinion_max_size_KO'],
    ['opinion', 'fecha_opinion', 'input', 414, 'cumple formato', 'SEARCH', 'fecha_opinion_format_KO'],
    ['opinion', 'conclusiones', 'input', 415, 'cumple tamaño maximo', 'SEARCH', 'conclusiones_max_size_KO'],
    ['opinion', 'conclusiones', 'input', 416, 'cumple formato', 'SEARCH', 'conclusiones_format_KO']
);

let opinion_tests_fields = Array(
    ['opinion', 'fecha_opinion', 27, 27, 'ADD', [{ fecha_opinion: 'fecha_erronea' }], 'fecha_opinion_format_KO'],
    ['opinion', 'fecha_opinion', 28, 28, 'ADD', [{ fecha_opinion: '2026-01-01' }], true],
    ['opinion', 'fecha_opinion', 29, 29, 'EDIT', [{ fecha_opinion: 'fecha_erronea' }], 'fecha_opinion_format_KO'],
    ['opinion', 'fecha_opinion', 30, 30, 'EDIT', [{ fecha_opinion: '2026-01-01' }], true],
    ['opinion', 'conclusiones', 31, 31, 'ADD', [{ conclusiones: '' }], 'conclusiones_min_size_KO'],
    ['opinion', 'conclusiones', 32, 32, 'ADD', [{ conclusiones: 'C'.repeat(201) }], 'conclusiones_max_size_KO'],
    ['opinion', 'conclusiones', 33, 33, 'ADD', [{ conclusiones: '###@@@' }], 'conclusiones_format_KO'],
    ['opinion', 'conclusiones', 34, 34, 'ADD', [{ conclusiones: 'Conclusión correcta' }], true],
    ['opinion', 'conclusiones', 35, 35, 'EDIT', [{ conclusiones: '' }], 'conclusiones_min_size_KO'],
    ['opinion', 'conclusiones', 36, 36, 'EDIT', [{ conclusiones: 'C'.repeat(201) }], 'conclusiones_max_size_KO'],
    ['opinion', 'conclusiones', 37, 37, 'EDIT', [{ conclusiones: '###@@@' }], 'conclusiones_format_KO'],
    ['opinion', 'conclusiones', 38, 38, 'EDIT', [{ conclusiones: 'Conclusión correcta' }], true],
    ['opinion', 'fecha_opinion', 352, 352, 'SEARCH', [{ fecha_opinion: '' }], true],
    ['opinion', 'conclusiones', 353, 353, 'SEARCH', [{ conclusiones: '' }], true],
    ['opinion', 'conclusiones', 403, 403, 'SEARCH', [{ conclusiones: 'buena' }], true],
    ['opinion', 'fecha_opinion', 413, 413, 'SEARCH', [{ fecha_opinion: '1'.repeat(11) }], 'fecha_opinion_max_size_KO'],
    ['opinion', 'fecha_opinion', 414, 414, 'SEARCH', [{ fecha_opinion: 'abc/def' }], 'fecha_opinion_format_KO'],
    ['opinion', 'conclusiones', 415, 415, 'SEARCH', [{ conclusiones: 'c'.repeat(201) }], 'conclusiones_max_size_KO'],
    ['opinion', 'conclusiones', 416, 416, 'SEARCH', [{ conclusiones: '#@@@' }], 'conclusiones_format_KO']
);

let opinion_tests_files = Array();

let parametro_def_tests = Array(
    ['parametro', 'nombre', 'input', 39, 'cumple tamaño minimo', 'ADD', 'nombre_min_size_KO'],
    ['parametro', 'nombre', 'input', 40, 'cumple tamaño maximo', 'ADD', 'nombre_max_size_KO'],
    ['parametro', 'nombre', 'input', 41, 'cumple formato', 'ADD', 'nombre_format_KO'],
    ['parametro', 'nombre', 'input', 42, 'es correcto', 'ADD', true],
    ['parametro', 'nombre', 'input', 43, 'cumple tamaño minimo', 'EDIT', 'nombre_min_size_KO'],
    ['parametro', 'nombre', 'input', 44, 'cumple tamaño maximo', 'EDIT', 'nombre_max_size_KO'],
    ['parametro', 'nombre', 'input', 45, 'cumple formato', 'EDIT', 'nombre_format_KO'],
    ['parametro', 'nombre', 'input', 46, 'es correcto', 'EDIT', true],
    ['parametro', 'unidad', 'input', 47, 'cumple tamaño minimo', 'ADD', 'unidad_min_size_KO'],
    ['parametro', 'unidad', 'input', 48, 'cumple tamaño maximo', 'ADD', 'unidad_max_size_KO'],
    ['parametro', 'unidad', 'input', 49, 'cumple formato', 'ADD', 'unidad_format_KO'],
    ['parametro', 'unidad', 'input', 50, 'es correcto', 'ADD', true],
    ['parametro', 'unidad', 'input', 51, 'cumple tamaño minimo', 'EDIT', 'unidad_min_size_KO'],
    ['parametro', 'unidad', 'input', 52, 'cumple tamaño maximo', 'EDIT', 'unidad_max_size_KO'],
    ['parametro', 'unidad', 'input', 53, 'cumple formato', 'EDIT', 'unidad_format_KO'],
    ['parametro', 'unidad', 'input', 54, 'es correcto', 'EDIT', true],
    ['parametro', 'acronimo', 'input', 55, 'cumple tamaño minimo', 'ADD', 'acronimo_min_size_KO'],
    ['parametro', 'acronimo', 'input', 56, 'cumple tamaño maximo', 'ADD', 'acronimo_max_size_KO'],
    ['parametro', 'acronimo', 'input', 57, 'cumple formato', 'ADD', 'acronimo_format_KO'],
    ['parametro', 'acronimo', 'input', 58, 'es correcto', 'ADD', true],
    ['parametro', 'acronimo', 'input', 59, 'cumple tamaño minimo', 'EDIT', 'acronimo_min_size_KO'],
    ['parametro', 'acronimo', 'input', 60, 'cumple tamaño maximo', 'EDIT', 'acronimo_max_size_KO'],
    ['parametro', 'acronimo', 'input', 61, 'cumple formato', 'EDIT', 'acronimo_format_KO'],
    ['parametro', 'acronimo', 'input', 62, 'es correcto', 'EDIT', true],
    ['parametro', 'descripcion', 'input', 63, 'cumple tamaño minimo', 'ADD', 'descripcion_min_size_KO'],
    ['parametro', 'descripcion', 'input', 64, 'cumple tamaño maximo', 'ADD', 'descripcion_max_size_KO'],
    ['parametro', 'descripcion', 'input', 65, 'cumple formato', 'ADD', 'descripcion_format_KO'],
    ['parametro', 'descripcion', 'input', 66, 'es correcto', 'ADD', true],
    ['parametro', 'descripcion', 'input', 67, 'cumple tamaño minimo', 'EDIT', 'descripcion_min_size_KO'],
    ['parametro', 'descripcion', 'input', 68, 'cumple tamaño maximo', 'EDIT', 'descripcion_max_size_KO'],
    ['parametro', 'descripcion', 'input', 69, 'cumple formato', 'EDIT', 'descripcion_format_KO'],
    ['parametro', 'descripcion', 'input', 70, 'es correcto', 'EDIT', true],
    ['parametro', 'rango_min_optimo', 'input', 71, 'cumple formato', 'ADD', 'rango_min_optimo_format_KO'],
    ['parametro', 'rango_min_optimo', 'input', 72, 'es correcto', 'ADD', true],
    ['parametro', 'rango_min_optimo', 'input', 73, 'cumple formato', 'EDIT', 'rango_min_optimo_format_KO'],
    ['parametro', 'rango_min_optimo', 'input', 74, 'es correcto', 'EDIT', true],
    ['parametro', 'rango_max_optimo', 'input', 75, 'cumple formato', 'ADD', 'rango_max_optimo_format_KO'],
    ['parametro', 'rango_max_optimo', 'input', 76, 'es correcto', 'ADD', true],
    ['parametro', 'rango_max_optimo', 'input', 77, 'cumple formato', 'EDIT', 'rango_max_optimo_format_KO'],
    ['parametro', 'rango_max_optimo', 'input', 78, 'es correcto', 'EDIT', true],
    ['parametro', 'nombre', 'input', 354, 'es correcto vacío', 'SEARCH', true],
    ['parametro', 'unidad', 'input', 355, 'es correcto vacío', 'SEARCH', true],
    ['parametro', 'acronimo', 'input', 356, 'es correcto vacío', 'SEARCH', true],
    ['parametro', 'descripcion', 'input', 357, 'es correcto vacío', 'SEARCH', true],
    ['parametro', 'rango_min_optimo', 'input', 358, 'es correcto vacío', 'SEARCH', true],
    ['parametro', 'rango_max_optimo', 'input', 359, 'es correcto vacío', 'SEARCH', true],
    ['parametro', 'nombre', 'input', 404, 'es correcto como substring', 'SEARCH', true],
    ['parametro', 'nombre', 'input', 417, 'cumple tamaño maximo', 'SEARCH', 'nombre_max_size_KO'],
    ['parametro', 'nombre', 'input', 418, 'cumple formato', 'SEARCH', 'nombre_format_KO'],
    ['parametro', 'unidad', 'input', 419, 'cumple tamaño maximo', 'SEARCH', 'unidad_max_size_KO'],
    ['parametro', 'unidad', 'input', 420, 'cumple formato', 'SEARCH', 'unidad_format_KO'],
    ['parametro', 'acronimo', 'input', 421, 'cumple tamaño maximo', 'SEARCH', 'acronimo_max_size_KO'],
    ['parametro', 'acronimo', 'input', 422, 'cumple formato', 'SEARCH', 'acronimo_format_KO'],
    ['parametro', 'descripcion', 'input', 423, 'cumple tamaño maximo', 'SEARCH', 'descripcion_max_size_KO'],
    ['parametro', 'descripcion', 'input', 424, 'cumple formato', 'SEARCH', 'descripcion_format_KO'],
    ['parametro', 'rango_min_optimo', 'input', 425, 'cumple tamaño maximo', 'SEARCH', 'rango_min_optimo_max_size_KO'],
    ['parametro', 'rango_min_optimo', 'input', 426, 'cumple formato', 'SEARCH', 'rango_min_optimo_format_KO'],
    ['parametro', 'rango_max_optimo', 'input', 427, 'cumple tamaño maximo', 'SEARCH', 'rango_max_optimo_max_size_KO'],
    ['parametro', 'rango_max_optimo', 'input', 428, 'cumple formato', 'SEARCH', 'rango_max_optimo_format_KO']
);

let parametro_tests_fields = Array(
    ['parametro', 'nombre', 39, 39, 'ADD', [{ nombre: 'ab' }], 'nombre_min_size_KO'],
    ['parametro', 'nombre', 40, 40, 'ADD', [{ nombre: 'N'.repeat(51) }], 'nombre_max_size_KO'],
    ['parametro', 'nombre', 41, 41, 'ADD', [{ nombre: '!!!123' }], 'nombre_format_KO'],
    ['parametro', 'nombre', 42, 42, 'ADD', [{ nombre: 'Temperatura' }], true],
    ['parametro', 'nombre', 43, 43, 'EDIT', [{ nombre: 'ab' }], 'nombre_min_size_KO'],
    ['parametro', 'nombre', 44, 44, 'EDIT', [{ nombre: 'N'.repeat(51) }], 'nombre_max_size_KO'],
    ['parametro', 'nombre', 45, 45, 'EDIT', [{ nombre: '!!!123' }], 'nombre_format_KO'],
    ['parametro', 'nombre', 46, 46, 'EDIT', [{ nombre: 'Temperatura' }], true],
    ['parametro', 'unidad', 47, 47, 'ADD', [{ unidad: '' }], 'unidad_min_size_KO'],
    ['parametro', 'unidad', 48, 48, 'ADD', [{ unidad: 'U'.repeat(21) }], 'unidad_max_size_KO'],
    ['parametro', 'unidad', 49, 49, 'ADD', [{ unidad: '%&/' }], 'unidad_format_KO'],
    ['parametro', 'unidad', 50, 50, 'ADD', [{ unidad: 'Grados' }], true],
    ['parametro', 'unidad', 51, 51, 'EDIT', [{ unidad: '' }], 'unidad_min_size_KO'],
    ['parametro', 'unidad', 52, 52, 'EDIT', [{ unidad: 'U'.repeat(21) }], 'unidad_max_size_KO'],
    ['parametro', 'unidad', 53, 53, 'EDIT', [{ unidad: '%&/' }], 'unidad_format_KO'],
    ['parametro', 'unidad', 54, 54, 'EDIT', [{ unidad: 'Grados' }], true],
    ['parametro', 'acronimo', 55, 55, 'ADD', [{ acronimo: '' }], 'acronimo_min_size_KO'],
    ['parametro', 'acronimo', 56, 56, 'ADD', [{ acronimo: 'A'.repeat(11) }], 'acronimo_max_size_KO'],
    ['parametro', 'acronimo', 57, 57, 'ADD', [{ acronimo: '().' }], 'acronimo_format_KO'],
    ['parametro', 'acronimo', 58, 58, 'ADD', [{ acronimo: 'TEMP' }], true],
    ['parametro', 'acronimo', 59, 59, 'EDIT', [{ acronimo: '' }], 'acronimo_min_size_KO'],
    ['parametro', 'acronimo', 60, 60, 'EDIT', [{ acronimo: 'A'.repeat(11) }], 'acronimo_max_size_KO'],
    ['parametro', 'acronimo', 61, 61, 'EDIT', [{ acronimo: '().' }], 'acronimo_format_KO'],
    ['parametro', 'acronimo', 62, 62, 'EDIT', [{ acronimo: 'TEMP' }], true],
    ['parametro', 'descripcion', 63, 63, 'ADD', [{ descripcion: '' }], 'descripcion_min_size_KO'],
    ['parametro', 'descripcion', 64, 64, 'ADD', [{ descripcion: 'D'.repeat(201) }], 'descripcion_max_size_KO'],
    ['parametro', 'descripcion', 65, 65, 'ADD', [{ descripcion: '{}[][]' }], 'descripcion_format_KO'],
    ['parametro', 'descripcion', 66, 66, 'ADD', [{ descripcion: 'Descripcion val' }], true],
    ['parametro', 'descripcion', 67, 67, 'EDIT', [{ descripcion: '' }], 'descripcion_min_size_KO'],
    ['parametro', 'descripcion', 68, 68, 'EDIT', [{ descripcion: 'D'.repeat(201) }], 'descripcion_max_size_KO'],
    ['parametro', 'descripcion', 69, 69, 'EDIT', [{ descripcion: '{}[][]' }], 'descripcion_format_KO'],
    ['parametro', 'descripcion', 70, 70, 'EDIT', [{ descripcion: 'Descripcion val' }], true],
    ['parametro', 'rango_min_optimo', 71, 71, 'ADD', [{ rango_min_optimo: 'texto' }], 'rango_min_optimo_format_KO'],
    ['parametro', 'rango_min_optimo', 72, 72, 'ADD', [{ rango_min_optimo: '10' }], true],
    ['parametro', 'rango_min_optimo', 73, 73, 'EDIT', [{ rango_min_optimo: 'texto' }], 'rango_min_optimo_format_KO'],
    ['parametro', 'rango_min_optimo', 74, 74, 'EDIT', [{ rango_min_optimo: '10' }], true],
    ['parametro', 'rango_max_optimo', 75, 75, 'ADD', [{ rango_max_optimo: 'letras' }], 'rango_max_optimo_format_KO'],
    ['parametro', 'rango_max_optimo', 76, 76, 'ADD', [{ rango_max_optimo: '50' }], true],
    ['parametro', 'rango_max_optimo', 77, 77, 'EDIT', [{ rango_max_optimo: 'letras' }], 'rango_max_optimo_format_KO'],
    ['parametro', 'rango_max_optimo', 78, 78, 'EDIT', [{ rango_max_optimo: '50' }], true],
    ['parametro', 'nombre', 354, 354, 'SEARCH', [{ nombre: '' }], true],
    ['parametro', 'unidad', 355, 355, 'SEARCH', [{ unidad: '' }], true],
    ['parametro', 'acronimo', 356, 356, 'SEARCH', [{ acronimo: '' }], true],
    ['parametro', 'descripcion', 357, 357, 'SEARCH', [{ descripcion: '' }], true],
    ['parametro', 'rango_min_optimo', 358, 358, 'SEARCH', [{ rango_min_optimo: '' }], true],
    ['parametro', 'rango_max_optimo', 359, 359, 'SEARCH', [{ rango_max_optimo: '' }], true],
    ['parametro', 'nombre', 404, 404, 'SEARCH', [{ nombre: 'pH' }], true],
    ['parametro', 'nombre', 417, 417, 'SEARCH', [{ nombre: 'n'.repeat(51) }], 'nombre_max_size_KO'],
    ['parametro', 'nombre', 418, 418, 'SEARCH', [{ nombre: '{{{{{' }], 'nombre_format_KO'],
    ['parametro', 'unidad', 419, 419, 'SEARCH', [{ unidad: 'u'.repeat(21) }], 'unidad_max_size_KO'],
    ['parametro', 'unidad', 420, 420, 'SEARCH', [{ unidad: '###' }], 'unidad_format_KO'],
    ['parametro', 'acronimo', 421, 421, 'SEARCH', [{ acronimo: 'a'.repeat(11) }], 'acronimo_max_size_KO'],
    ['parametro', 'acronimo', 422, 422, 'SEARCH', [{ acronimo: '##' }], 'acronimo_format_KO'],
    ['parametro', 'descripcion', 423, 423, 'SEARCH', [{ descripcion: 'd'.repeat(201) }], 'descripcion_max_size_KO'],
    ['parametro', 'descripcion', 424, 424, 'SEARCH', [{ descripcion: '<tag>' }], 'descripcion_format_KO'],
    ['parametro', 'rango_min_optimo', 425, 425, 'SEARCH', [{ rango_min_optimo: '1'.repeat(21) }], 'rango_min_optimo_max_size_KO'],
    ['parametro', 'rango_min_optimo', 426, 426, 'SEARCH', [{ rango_min_optimo: 'abc' }], 'rango_min_optimo_format_KO'],
    ['parametro', 'rango_max_optimo', 427, 427, 'SEARCH', [{ rango_max_optimo: '1'.repeat(21) }], 'rango_max_optimo_max_size_KO'],
    ['parametro', 'rango_max_optimo', 428, 428, 'SEARCH', [{ rango_max_optimo: 'abc' }], 'rango_max_optimo_format_KO']
);

let parametro_tests_files = Array();

let parcela_def_tests = Array(
    ['parcela', 'usuario_login', 'input', 79, 'cumple tamaño minimo', 'ADD', 'usuario_login_min_size_KO'],
    ['parcela', 'usuario_login', 'input', 80, 'cumple tamaño maximo', 'ADD', 'usuario_login_max_size_KO'],
    ['parcela', 'usuario_login', 'input', 81, 'cumple formato', 'ADD', 'usuario_login_format_KO'],
    ['parcela', 'usuario_login', 'input', 82, 'es correcto', 'ADD', true],
    ['parcela', 'usuario_login', 'input', 83, 'cumple tamaño minimo', 'EDIT', 'usuario_login_min_size_KO'],
    ['parcela', 'usuario_login', 'input', 84, 'cumple tamaño maximo', 'EDIT', 'usuario_login_max_size_KO'],
    ['parcela', 'usuario_login', 'input', 85, 'cumple formato', 'EDIT', 'usuario_login_format_KO'],
    ['parcela', 'usuario_login', 'input', 86, 'es correcto', 'EDIT', true],
    ['parcela', 'nombre', 'input', 87, 'cumple tamaño minimo', 'ADD', 'nombre_min_size_KO'],
    ['parcela', 'nombre', 'input', 88, 'cumple tamaño maximo', 'ADD', 'nombre_max_size_KO'],
    ['parcela', 'nombre', 'input', 89, 'cumple formato', 'ADD', 'nombre_format_KO'],
    ['parcela', 'nombre', 'input', 90, 'es correcto', 'ADD', true],
    ['parcela', 'nombre', 'input', 91, 'cumple tamaño minimo', 'EDIT', 'nombre_min_size_KO'],
    ['parcela', 'nombre', 'input', 92, 'cumple tamaño maximo', 'EDIT', 'nombre_max_size_KO'],
    ['parcela', 'nombre', 'input', 93, 'cumple formato', 'EDIT', 'nombre_format_KO'],
    ['parcela', 'nombre', 'input', 94, 'es correcto', 'EDIT', true],
    ['parcela', 'latitud', 'input', 95, 'cumple formato', 'ADD', 'latitud_format_KO'],
    ['parcela', 'latitud', 'input', 96, 'es correcto', 'ADD', true],
    ['parcela', 'latitud', 'input', 97, 'cumple formato', 'EDIT', 'latitud_format_KO'],
    ['parcela', 'latitud', 'input', 98, 'es correcto', 'EDIT', true],
    ['parcela', 'longitud', 'input', 99, 'cumple formato', 'ADD', 'longitud_format_KO'],
    ['parcela', 'longitud', 'input', 100, 'es correcto', 'ADD', true],
    ['parcela', 'longitud', 'input', 101, 'cumple formato', 'EDIT', 'longitud_format_KO'],
    ['parcela', 'longitud', 'input', 102, 'es correcto', 'EDIT', true],
    ['parcela', 'altitud', 'input', 103, 'cumple formato', 'ADD', 'altitud_format_KO'],
    ['parcela', 'altitud', 'input', 104, 'es correcto', 'ADD', true],
    ['parcela', 'altitud', 'input', 105, 'cumple formato', 'EDIT', 'altitud_format_KO'],
    ['parcela', 'altitud', 'input', 106, 'es correcto', 'EDIT', true],
    ['parcela', 'localidad', 'input', 107, 'cumple tamaño minimo', 'ADD', 'localidad_min_size_KO'],
    ['parcela', 'localidad', 'input', 108, 'cumple tamaño maximo', 'ADD', 'localidad_max_size_KO'],
    ['parcela', 'localidad', 'input', 109, 'cumple formato', 'ADD', 'localidad_format_KO'],
    ['parcela', 'localidad', 'input', 110, 'es correcto', 'ADD', true],
    ['parcela', 'localidad', 'input', 111, 'cumple tamaño minimo', 'EDIT', 'localidad_min_size_KO'],
    ['parcela', 'localidad', 'input', 112, 'cumple tamaño maximo', 'EDIT', 'localidad_max_size_KO'],
    ['parcela', 'localidad', 'input', 113, 'cumple formato', 'EDIT', 'localidad_format_KO'],
    ['parcela', 'localidad', 'input', 114, 'es correcto', 'EDIT', true],
    ['parcela', 'provincia', 'input', 115, 'cumple tamaño minimo', 'ADD', 'provincia_min_size_KO'],
    ['parcela', 'provincia', 'input', 116, 'cumple tamaño maximo', 'ADD', 'provincia_max_size_KO'],
    ['parcela', 'provincia', 'input', 117, 'cumple formato', 'ADD', 'provincia_format_KO'],
    ['parcela', 'provincia', 'input', 118, 'es correcto', 'ADD', true],
    ['parcela', 'provincia', 'input', 119, 'cumple tamaño minimo', 'EDIT', 'provincia_min_size_KO'],
    ['parcela', 'provincia', 'input', 120, 'cumple tamaño maximo', 'EDIT', 'provincia_max_size_KO'],
    ['parcela', 'provincia', 'input', 121, 'cumple formato', 'EDIT', 'provincia_format_KO'],
    ['parcela', 'provincia', 'input', 122, 'es correcto', 'EDIT', true],
    ['parcela', 'foto_norte', 'inputfile', 123, 'existe fichero', 'ADD', 'foto_norte_not_exist_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 124, 'cumple nombre fichero', 'ADD', 'foto_norte_format_name_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 125, 'cumple tipo fichero', 'ADD', 'foto_norte_type_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 126, 'cumple tamaño maximo fichero', 'ADD', 'foto_norte_max_size_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 127, 'cumple tamaño minimo nombre', 'ADD', 'foto_norte_min_size_name_KO'],
    ['parcela', 'foto_norte', 'inputfile', 128, 'cumple tamaño maximo nombre', 'ADD', 'foto_norte_max_size_name_KO'],
    ['parcela', 'foto_norte', 'inputfile', 129, 'fichero ok', 'ADD', true],
    ['parcela', 'foto_norte', 'inputfile', 130, 'no existe fichero', 'EDIT', true],
    ['parcela', 'foto_norte', 'inputfile', 131, 'cumple nombre fichero', 'EDIT', 'foto_norte_format_name_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 132, 'cumple tipo fichero', 'EDIT', 'foto_norte_type_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 133, 'cumple tamaño maximo fichero', 'EDIT', 'foto_norte_max_size_file_KO'],
    ['parcela', 'foto_norte', 'inputfile', 134, 'cumple tamaño minimo nombre', 'EDIT', 'foto_norte_min_size_name_KO'],
    ['parcela', 'foto_norte', 'inputfile', 135, 'cumple tamaño maximo nombre', 'EDIT', 'foto_norte_max_size_name_KO'],
    ['parcela', 'foto_norte', 'inputfile', 136, 'fichero ok', 'EDIT', true],
    ['parcela', 'foto_sur', 'inputfile', 137, 'existe fichero', 'ADD', 'foto_sur_not_exist_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 138, 'cumple nombre fichero', 'ADD', 'foto_sur_format_name_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 139, 'cumple tipo fichero', 'ADD', 'foto_sur_type_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 140, 'cumple tamaño maximo fichero', 'ADD', 'foto_sur_max_size_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 141, 'cumple tamaño minimo nombre', 'ADD', 'foto_sur_min_size_name_KO'],
    ['parcela', 'foto_sur', 'inputfile', 142, 'cumple tamaño maximo nombre', 'ADD', 'foto_sur_max_size_name_KO'],
    ['parcela', 'foto_sur', 'inputfile', 143, 'fichero ok', 'ADD', true],
    ['parcela', 'foto_sur', 'inputfile', 144, 'no existe fichero', 'EDIT', true],
    ['parcela', 'foto_sur', 'inputfile', 145, 'cumple nombre fichero', 'EDIT', 'foto_sur_format_name_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 146, 'cumple tipo fichero', 'EDIT', 'foto_sur_type_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 147, 'cumple tamaño maximo fichero', 'EDIT', 'foto_sur_max_size_file_KO'],
    ['parcela', 'foto_sur', 'inputfile', 148, 'cumple tamaño minimo nombre', 'EDIT', 'foto_sur_min_size_name_KO'],
    ['parcela', 'foto_sur', 'inputfile', 149, 'cumple tamaño maximo nombre', 'EDIT', 'foto_sur_max_size_name_KO'],
    ['parcela', 'foto_sur', 'inputfile', 150, 'fichero ok', 'EDIT', true],
    ['parcela', 'foto_este', 'inputfile', 151, 'existe fichero', 'ADD', 'foto_este_not_exist_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 152, 'cumple nombre fichero', 'ADD', 'foto_este_format_name_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 153, 'cumple tipo fichero', 'ADD', 'foto_este_type_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 154, 'cumple tamaño maximo fichero', 'ADD', 'foto_este_max_size_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 155, 'cumple tamaño minimo nombre', 'ADD', 'foto_este_min_size_name_KO'],
    ['parcela', 'foto_este', 'inputfile', 156, 'cumple tamaño maximo nombre', 'ADD', 'foto_este_max_size_name_KO'],
    ['parcela', 'foto_este', 'inputfile', 157, 'fichero ok', 'ADD', true],
    ['parcela', 'foto_este', 'inputfile', 158, 'no existe fichero', 'EDIT', true],
    ['parcela', 'foto_este', 'inputfile', 159, 'cumple nombre fichero', 'EDIT', 'foto_este_format_name_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 160, 'cumple tipo fichero', 'EDIT', 'foto_este_type_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 161, 'cumple tamaño maximo fichero', 'EDIT', 'foto_este_max_size_file_KO'],
    ['parcela', 'foto_este', 'inputfile', 162, 'cumple tamaño minimo nombre', 'EDIT', 'foto_este_min_size_name_KO'],
    ['parcela', 'foto_este', 'inputfile', 163, 'cumple tamaño maximo nombre', 'EDIT', 'foto_este_max_size_name_KO'],
    ['parcela', 'foto_este', 'inputfile', 164, 'fichero ok', 'EDIT', true],
    ['parcela', 'foto_oeste', 'inputfile', 165, 'existe fichero', 'ADD', 'foto_oeste_not_exist_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 166, 'cumple nombre fichero', 'ADD', 'foto_oeste_format_name_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 167, 'cumple tipo fichero', 'ADD', 'foto_oeste_type_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 168, 'cumple tamaño maximo fichero', 'ADD', 'foto_oeste_max_size_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 169, 'cumple tamaño minimo nombre', 'ADD', 'foto_oeste_min_size_name_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 170, 'cumple tamaño maximo nombre', 'ADD', 'foto_oeste_max_size_name_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 171, 'fichero ok', 'ADD', true],
    ['parcela', 'foto_oeste', 'inputfile', 172, 'no existe fichero', 'EDIT', true],
    ['parcela', 'foto_oeste', 'inputfile', 173, 'cumple nombre fichero', 'EDIT', 'foto_oeste_format_name_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 174, 'cumple tipo fichero', 'EDIT', 'foto_oeste_type_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 175, 'cumple tamaño maximo fichero', 'EDIT', 'foto_oeste_max_size_file_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 176, 'cumple tamaño minimo nombre', 'EDIT', 'foto_oeste_min_size_name_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 177, 'cumple tamaño maximo nombre', 'EDIT', 'foto_oeste_max_size_name_KO'],
    ['parcela', 'foto_oeste', 'inputfile', 178, 'fichero ok', 'EDIT', true],
    ['parcela', 'superficie_ha', 'input', 179, 'cumple formato', 'ADD', 'superficie_ha_format_KO'],
    ['parcela', 'superficie_ha', 'input', 180, 'es correcto', 'ADD', true],
    ['parcela', 'superficie_ha', 'input', 181, 'cumple formato', 'EDIT', 'superficie_ha_format_KO'],
    ['parcela', 'superficie_ha', 'input', 182, 'es correcto', 'EDIT', true],
    ['parcela', 'usuario_login', 'input', 360, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'nombre', 'input', 361, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'latitud', 'input', 362, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'longitud', 'input', 363, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'altitud', 'input', 364, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'localidad', 'input', 365, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'provincia', 'input', 366, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'foto_norte', 'inputfile', 367, 'es correcto sin fichero', 'SEARCH', true],
    ['parcela', 'foto_sur', 'inputfile', 368, 'es correcto sin fichero', 'SEARCH', true],
    ['parcela', 'foto_este', 'inputfile', 369, 'es correcto sin fichero', 'SEARCH', true],
    ['parcela', 'foto_oeste', 'inputfile', 370, 'es correcto sin fichero', 'SEARCH', true],
    ['parcela', 'superficie_ha', 'input', 371, 'es correcto vacío', 'SEARCH', true],
    ['parcela', 'localidad', 'input', 405, 'es correcto como substring', 'SEARCH', true],
    ['parcela', 'usuario_login', 'input', 429, 'cumple tamaño maximo', 'SEARCH', 'usuario_login_max_size_KO'],
    ['parcela', 'usuario_login', 'input', 430, 'cumple formato', 'SEARCH', 'usuario_login_format_KO'],
    ['parcela', 'nombre', 'input', 431, 'cumple tamaño maximo', 'SEARCH', 'nombre_max_size_KO'],
    ['parcela', 'nombre', 'input', 432, 'cumple formato', 'SEARCH', 'nombre_format_KO'],
    ['parcela', 'latitud', 'input', 433, 'cumple tamaño maximo', 'SEARCH', 'latitud_max_size_KO'],
    ['parcela', 'latitud', 'input', 434, 'cumple formato', 'SEARCH', 'latitud_format_KO'],
    ['parcela', 'longitud', 'input', 435, 'cumple tamaño maximo', 'SEARCH', 'longitud_max_size_KO'],
    ['parcela', 'longitud', 'input', 436, 'cumple formato', 'SEARCH', 'longitud_format_KO'],
    ['parcela', 'altitud', 'input', 437, 'cumple tamaño maximo', 'SEARCH', 'altitud_max_size_KO'],
    ['parcela', 'altitud', 'input', 438, 'cumple formato', 'SEARCH', 'altitud_format_KO'],
    ['parcela', 'localidad', 'input', 439, 'cumple tamaño maximo', 'SEARCH', 'localidad_max_size_KO'],
    ['parcela', 'localidad', 'input', 440, 'cumple formato', 'SEARCH', 'localidad_format_KO'],
    ['parcela', 'provincia', 'input', 441, 'cumple tamaño maximo', 'SEARCH', 'provincia_max_size_KO'],
    ['parcela', 'provincia', 'input', 442, 'cumple formato', 'SEARCH', 'provincia_format_KO'],
    ['parcela', 'superficie_ha', 'input', 443, 'cumple tamaño maximo', 'SEARCH', 'superficie_ha_max_size_KO'],
    ['parcela', 'superficie_ha', 'input', 444, 'cumple formato', 'SEARCH', 'superficie_ha_format_KO']
);

let parcela_tests_fields = Array(
    ['parcela', 'usuario_login', 79, 79, 'ADD', [{ usuario_login: 'lo' }], 'usuario_login_min_size_KO'],
    ['parcela', 'usuario_login', 80, 80, 'ADD', [{ usuario_login: 'U'.repeat(31) }], 'usuario_login_max_size_KO'],
    ['parcela', 'usuario_login', 81, 81, 'ADD', [{ usuario_login: '@@login' }], 'usuario_login_format_KO'],
    ['parcela', 'usuario_login', 82, 82, 'ADD', [{ usuario_login: 'jrodeiro' }], true],
    ['parcela', 'usuario_login', 83, 83, 'EDIT', [{ usuario_login: 'lo' }], 'usuario_login_min_size_KO'],
    ['parcela', 'usuario_login', 84, 84, 'EDIT', [{ usuario_login: 'U'.repeat(31) }], 'usuario_login_max_size_KO'],
    ['parcela', 'usuario_login', 85, 85, 'EDIT', [{ usuario_login: '@@login' }], 'usuario_login_format_KO'],
    ['parcela', 'usuario_login', 86, 86, 'EDIT', [{ usuario_login: 'jrodeiro' }], true],
    ['parcela', 'nombre', 87, 87, 'ADD', [{ nombre: 'no' }], 'nombre_min_size_KO'],
    ['parcela', 'nombre', 88, 88, 'ADD', [{ nombre: 'N'.repeat(51) }], 'nombre_max_size_KO'],
    ['parcela', 'nombre', 89, 89, 'ADD', [{ nombre: '()()' }], 'nombre_format_KO'],
    ['parcela', 'nombre', 90, 90, 'ADD', [{ nombre: 'Parcela Norte' }], true],
    ['parcela', 'nombre', 91, 91, 'EDIT', [{ nombre: 'no' }], 'nombre_min_size_KO'],
    ['parcela', 'nombre', 92, 92, 'EDIT', [{ nombre: 'N'.repeat(51) }], 'nombre_max_size_KO'],
    ['parcela', 'nombre', 93, 93, 'EDIT', [{ nombre: '()()' }], 'nombre_format_KO'],
    ['parcela', 'nombre', 94, 94, 'EDIT', [{ nombre: 'Parcela Norte' }], true],
    ['parcela', 'latitud', 95, 95, 'ADD', [{ latitud: 'lat' }], 'latitud_format_KO'],
    ['parcela', 'latitud', 96, 96, 'ADD', [{ latitud: '42.123' }], true],
    ['parcela', 'latitud', 97, 97, 'EDIT', [{ latitud: 'lat' }], 'latitud_format_KO'],
    ['parcela', 'latitud', 98, 98, 'EDIT', [{ latitud: '42.123' }], true],
    ['parcela', 'longitud', 99, 99, 'ADD', [{ longitud: 'lon' }], 'longitud_format_KO'],
    ['parcela', 'longitud', 100, 100, 'ADD', [{ longitud: '-8.123' }], true],
    ['parcela', 'longitud', 101, 101, 'EDIT', [{ longitud: 'lon' }], 'longitud_format_KO'],
    ['parcela', 'longitud', 102, 102, 'EDIT', [{ longitud: '-8.123' }], true],
    ['parcela', 'altitud', 103, 103, 'ADD', [{ altitud: 'alt' }], 'altitud_format_KO'],
    ['parcela', 'altitud', 104, 104, 'ADD', [{ altitud: '500' }], true],
    ['parcela', 'altitud', 105, 105, 'EDIT', [{ altitud: 'alt' }], 'altitud_format_KO'],
    ['parcela', 'altitud', 106, 106, 'EDIT', [{ altitud: '500' }], true],
    ['parcela', 'localidad', 107, 107, 'ADD', [{ localidad: 'lo' }], 'localidad_min_size_KO'],
    ['parcela', 'localidad', 108, 108, 'ADD', [{ localidad: 'L'.repeat(41) }], 'localidad_max_size_KO'],
    ['parcela', 'localidad', 109, 109, 'ADD', [{ localidad: '????' }], 'localidad_format_KO'],
    ['parcela', 'localidad', 110, 110, 'ADD', [{ localidad: 'Vigo' }], true],
    ['parcela', 'localidad', 111, 111, 'EDIT', [{ localidad: 'lo' }], 'localidad_min_size_KO'],
    ['parcela', 'localidad', 112, 112, 'EDIT', [{ localidad: 'L'.repeat(41) }], 'localidad_max_size_KO'],
    ['parcela', 'localidad', 113, 113, 'EDIT', [{ localidad: '????' }], 'localidad_format_KO'],
    ['parcela', 'localidad', 114, 114, 'EDIT', [{ localidad: 'Vigo' }], true],
    ['parcela', 'provincia', 115, 115, 'ADD', [{ provincia: 'pr' }], 'provincia_min_size_KO'],
    ['parcela', 'provincia', 116, 116, 'ADD', [{ provincia: 'P'.repeat(31) }], 'provincia_max_size_KO'],
    ['parcela', 'provincia', 117, 117, 'ADD', [{ provincia: '!!!' }], 'provincia_format_KO'],
    ['parcela', 'provincia', 118, 118, 'ADD', [{ provincia: 'Pontevedra' }], true],
    ['parcela', 'provincia', 119, 119, 'EDIT', [{ provincia: 'pr' }], 'provincia_min_size_KO'],
    ['parcela', 'provincia', 120, 120, 'EDIT', [{ provincia: 'P'.repeat(31) }], 'provincia_max_size_KO'],
    ['parcela', 'provincia', 121, 121, 'EDIT', [{ provincia: '!!!' }], 'provincia_format_KO'],
    ['parcela', 'provincia', 122, 122, 'EDIT', [{ provincia: 'Pontevedra' }], true],
    ['parcela', 'superficie_ha', 179, 179, 'ADD', [{ superficie_ha: 'sup' }], 'superficie_ha_format_KO'],
    ['parcela', 'superficie_ha', 180, 180, 'ADD', [{ superficie_ha: '10.5' }], true],
    ['parcela', 'superficie_ha', 181, 181, 'EDIT', [{ superficie_ha: 'sup' }], 'superficie_ha_format_KO'],
    ['parcela', 'superficie_ha', 182, 182, 'EDIT', [{ superficie_ha: '10.5' }], true],
    ['parcela', 'usuario_login', 360, 360, 'SEARCH', [{ usuario_login: '' }], true],
    ['parcela', 'nombre', 361, 361, 'SEARCH', [{ nombre: '' }], true],
    ['parcela', 'latitud', 362, 362, 'SEARCH', [{ latitud: '' }], true],
    ['parcela', 'longitud', 363, 363, 'SEARCH', [{ longitud: '' }], true],
    ['parcela', 'altitud', 364, 364, 'SEARCH', [{ altitud: '' }], true],
    ['parcela', 'localidad', 365, 365, 'SEARCH', [{ localidad: '' }], true],
    ['parcela', 'provincia', 366, 366, 'SEARCH', [{ provincia: '' }], true],
    ['parcela', 'superficie_ha', 371, 371, 'SEARCH', [{ superficie_ha: '' }], true],
    ['parcela', 'localidad', 405, 405, 'SEARCH', [{ localidad: 'Vigo' }], true],
    ['parcela', 'usuario_login', 429, 429, 'SEARCH', [{ usuario_login: 'l'.repeat(31) }], 'usuario_login_max_size_KO'],
    ['parcela', 'usuario_login', 430, 430, 'SEARCH', [{ usuario_login: '##login' }], 'usuario_login_format_KO'],
    ['parcela', 'nombre', 431, 431, 'SEARCH', [{ nombre: 'n'.repeat(51) }], 'nombre_max_size_KO'],
    ['parcela', 'nombre', 432, 432, 'SEARCH', [{ nombre: '{{{{{' }], 'nombre_format_KO'],
    ['parcela', 'latitud', 433, 433, 'SEARCH', [{ latitud: '1'.repeat(16) }], 'latitud_max_size_KO'],
    ['parcela', 'latitud', 434, 434, 'SEARCH', [{ latitud: 'abc' }], 'latitud_format_KO'],
    ['parcela', 'longitud', 435, 435, 'SEARCH', [{ longitud: '1'.repeat(16) }], 'longitud_max_size_KO'],
    ['parcela', 'longitud', 436, 436, 'SEARCH', [{ longitud: 'abc' }], 'longitud_format_KO'],
    ['parcela', 'altitud', 437, 437, 'SEARCH', [{ altitud: '1'.repeat(11) }], 'altitud_max_size_KO'],
    ['parcela', 'altitud', 438, 438, 'SEARCH', [{ altitud: '12.5' }], 'altitud_format_KO'],
    ['parcela', 'localidad', 439, 439, 'SEARCH', [{ localidad: 'l'.repeat(41) }], 'localidad_max_size_KO'],
    ['parcela', 'localidad', 440, 440, 'SEARCH', [{ localidad: '123' }], 'localidad_format_KO'],
    ['parcela', 'provincia', 441, 441, 'SEARCH', [{ provincia: 'p'.repeat(31) }], 'provincia_max_size_KO'],
    ['parcela', 'provincia', 442, 442, 'SEARCH', [{ provincia: '123' }], 'provincia_format_KO'],
    ['parcela', 'superficie_ha', 443, 443, 'SEARCH', [{ superficie_ha: '1'.repeat(16) }], 'superficie_ha_max_size_KO'],
    ['parcela', 'superficie_ha', 444, 444, 'SEARCH', [{ superficie_ha: 'abc' }], 'superficie_ha_format_KO']
);

let parcela_tests_files = Array(
    ['parcela', 'foto_norte', 123, 123, 'ADD', 'existe', [], 'foto_norte_not_exist_file_KO'],
    ['parcela', 'foto_norte', 124, 124, 'ADD', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_norte_format_name_file_KO'],
    ['parcela', 'foto_norte', 125, 125, 'ADD', 'type_file', [{ format_name_file: 'imgN.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_norte_type_file_KO'],
    ['parcela', 'foto_norte', 126, 126, 'ADD', 'max_size_file', [{ format_name_file: 'imgN.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_norte_max_size_file_KO'],
    ['parcela', 'foto_norte', 127, 127, 'ADD', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_norte_min_size_name_KO'],
    ['parcela', 'foto_norte', 128, 128, 'ADD', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_norte_max_size_name_KO'],
    ['parcela', 'foto_norte', 129, 129, 'ADD', 'fichero ok', [{ format_name_file: 'imgN.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_norte', 130, 130, 'EDIT', 'noexiste', [], true],
    ['parcela', 'foto_norte', 131, 131, 'EDIT', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_norte_format_name_file_KO'],
    ['parcela', 'foto_norte', 132, 132, 'EDIT', 'type_file', [{ format_name_file: 'imgN.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_norte_type_file_KO'],
    ['parcela', 'foto_norte', 133, 133, 'EDIT', 'max_size_file', [{ format_name_file: 'imgN.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_norte_max_size_file_KO'],
    ['parcela', 'foto_norte', 134, 134, 'EDIT', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_norte_min_size_name_KO'],
    ['parcela', 'foto_norte', 135, 135, 'EDIT', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_norte_max_size_name_KO'],
    ['parcela', 'foto_norte', 136, 136, 'EDIT', 'fichero ok', [{ format_name_file: 'imgN.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_sur', 137, 137, 'ADD', 'existe', [], 'foto_sur_not_exist_file_KO'],
    ['parcela', 'foto_sur', 138, 138, 'ADD', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_sur_format_name_file_KO'],
    ['parcela', 'foto_sur', 139, 139, 'ADD', 'type_file', [{ format_name_file: 'imgS.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_sur_type_file_KO'],
    ['parcela', 'foto_sur', 140, 140, 'ADD', 'max_size_file', [{ format_name_file: 'imgS.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_sur_max_size_file_KO'],
    ['parcela', 'foto_sur', 141, 141, 'ADD', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_sur_min_size_name_KO'],
    ['parcela', 'foto_sur', 142, 142, 'ADD', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_sur_max_size_name_KO'],
    ['parcela', 'foto_sur', 143, 143, 'ADD', 'fichero ok', [{ format_name_file: 'imgS.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_sur', 144, 144, 'EDIT', 'noexiste', [], true],
    ['parcela', 'foto_sur', 145, 145, 'EDIT', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_sur_format_name_file_KO'],
    ['parcela', 'foto_sur', 146, 146, 'EDIT', 'type_file', [{ format_name_file: 'imgS.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_sur_type_file_KO'],
    ['parcela', 'foto_sur', 147, 147, 'EDIT', 'max_size_file', [{ format_name_file: 'imgS.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_sur_max_size_file_KO'],
    ['parcela', 'foto_sur', 148, 148, 'EDIT', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_sur_min_size_name_KO'],
    ['parcela', 'foto_sur', 149, 149, 'EDIT', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_sur_max_size_name_KO'],
    ['parcela', 'foto_sur', 150, 150, 'EDIT', 'fichero ok', [{ format_name_file: 'imgS.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_este', 151, 151, 'ADD', 'existe', [], 'foto_este_not_exist_file_KO'],
    ['parcela', 'foto_este', 152, 152, 'ADD', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_este_format_name_file_KO'],
    ['parcela', 'foto_este', 153, 153, 'ADD', 'type_file', [{ format_name_file: 'imgE.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_este_type_file_KO'],
    ['parcela', 'foto_este', 154, 154, 'ADD', 'max_size_file', [{ format_name_file: 'imgE.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_este_max_size_file_KO'],
    ['parcela', 'foto_este', 155, 155, 'ADD', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_este_min_size_name_KO'],
    ['parcela', 'foto_este', 156, 156, 'ADD', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_este_max_size_name_KO'],
    ['parcela', 'foto_este', 157, 157, 'ADD', 'fichero ok', [{ format_name_file: 'imgE.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_este', 158, 158, 'EDIT', 'noexiste', [], true],
    ['parcela', 'foto_este', 159, 159, 'EDIT', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_este_format_name_file_KO'],
    ['parcela', 'foto_este', 160, 160, 'EDIT', 'type_file', [{ format_name_file: 'imgE.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_este_type_file_KO'],
    ['parcela', 'foto_este', 161, 161, 'EDIT', 'max_size_file', [{ format_name_file: 'imgE.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_este_max_size_file_KO'],
    ['parcela', 'foto_este', 162, 162, 'EDIT', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_este_min_size_name_KO'],
    ['parcela', 'foto_este', 163, 163, 'EDIT', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_este_max_size_name_KO'],
    ['parcela', 'foto_este', 164, 164, 'EDIT', 'fichero ok', [{ format_name_file: 'imgE.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_oeste', 165, 165, 'ADD', 'existe', [], 'foto_oeste_not_exist_file_KO'],
    ['parcela', 'foto_oeste', 166, 166, 'ADD', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_oeste_format_name_file_KO'],
    ['parcela', 'foto_oeste', 167, 167, 'ADD', 'type_file', [{ format_name_file: 'imgO.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_oeste_type_file_KO'],
    ['parcela', 'foto_oeste', 168, 168, 'ADD', 'max_size_file', [{ format_name_file: 'imgO.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_oeste_max_size_file_KO'],
    ['parcela', 'foto_oeste', 169, 169, 'ADD', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_oeste_min_size_name_KO'],
    ['parcela', 'foto_oeste', 170, 170, 'ADD', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_oeste_max_size_name_KO'],
    ['parcela', 'foto_oeste', 171, 171, 'ADD', 'fichero ok', [{ format_name_file: 'imgO.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_oeste', 172, 172, 'EDIT', 'noexiste', [], true],
    ['parcela', 'foto_oeste', 173, 173, 'EDIT', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_oeste_format_name_file_KO'],
    ['parcela', 'foto_oeste', 174, 174, 'EDIT', 'type_file', [{ format_name_file: 'imgO.jpg' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'foto_oeste_type_file_KO'],
    ['parcela', 'foto_oeste', 175, 175, 'EDIT', 'max_size_file', [{ format_name_file: 'imgO.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 15000000 }], 'foto_oeste_max_size_file_KO'],
    ['parcela', 'foto_oeste', 176, 176, 'EDIT', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_oeste_min_size_name_KO'],
    ['parcela', 'foto_oeste', 177, 177, 'EDIT', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'foto_oeste_max_size_name_KO'],
    ['parcela', 'foto_oeste', 178, 178, 'EDIT', 'fichero ok', [{ format_name_file: 'imgO.jpg' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], true],
    ['parcela', 'foto_norte', 367, 367, 'SEARCH', 'noexiste', [], true],
    ['parcela', 'foto_sur', 368, 368, 'SEARCH', 'noexiste', [], true],
    ['parcela', 'foto_este', 369, 369, 'SEARCH', 'noexiste', [], true],
    ['parcela', 'foto_oeste', 370, 370, 'SEARCH', 'noexiste', [], true]
);

let parcela_proceso_def_tests = Array(
    ['parcela_proceso', 'fecha_aplicacion', 'input', 183, 'cumple formato', 'ADD', 'fecha_aplicacion_format_KO'],
    ['parcela_proceso', 'fecha_aplicacion', 'input', 184, 'es correcto', 'ADD', true],
    ['parcela_proceso', 'fecha_aplicacion', 'input', 185, 'cumple formato', 'EDIT', 'fecha_aplicacion_format_KO'],
    ['parcela_proceso', 'fecha_aplicacion', 'input', 186, 'es correcto', 'EDIT', true],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 187, 'cumple tamaño maximo', 'ADD', 'descripcion_aplicacion_max_size_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 188, 'es correcto', 'ADD', true],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 189, 'cumple tamaño maximo', 'EDIT', 'descripcion_aplicacion_max_size_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 190, 'es correcto', 'EDIT', true],
    ['parcela_proceso', 'comentarios', 'input', 191, 'cumple tamaño minimo', 'ADD', 'comentarios_min_size_KO'],
    ['parcela_proceso', 'comentarios', 'input', 192, 'cumple tamaño maximo', 'ADD', 'comentarios_max_size_KO'],
    ['parcela_proceso', 'comentarios', 'input', 193, 'cumple formato', 'ADD', 'comentarios_format_KO'],
    ['parcela_proceso', 'comentarios', 'input', 194, 'es correcto', 'ADD', true],
    ['parcela_proceso', 'comentarios', 'input', 195, 'cumple tamaño minimo', 'EDIT', 'comentarios_min_size_KO'],
    ['parcela_proceso', 'comentarios', 'input', 196, 'cumple tamaño maximo', 'EDIT', 'comentarios_max_size_KO'],
    ['parcela_proceso', 'comentarios', 'input', 197, 'cumple formato', 'EDIT', 'comentarios_format_KO'],
    ['parcela_proceso', 'comentarios', 'input', 198, 'es correcto', 'EDIT', true],
    ['parcela_proceso', 'fecha_aplicacion', 'input', 372, 'es correcto vacío', 'SEARCH', true],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 373, 'es correcto vacío', 'SEARCH', true],
    ['parcela_proceso', 'comentarios', 'input', 374, 'es correcto vacío', 'SEARCH', true],
    ['parcela_proceso', 'comentarios', 'input', 406, 'es correcto como substring', 'SEARCH', true],
    ['parcela_proceso', 'fecha_aplicacion', 'input', 445, 'cumple tamaño maximo', 'SEARCH', 'fecha_aplicacion_max_size_KO'],
    ['parcela_proceso', 'fecha_aplicacion', 'input', 446, 'cumple formato', 'SEARCH', 'fecha_aplicacion_format_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 447, 'cumple tamaño maximo', 'SEARCH', 'descripcion_aplicacion_max_size_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 'input', 448, 'cumple formato', 'SEARCH', 'descripcion_aplicacion_format_KO'],
    ['parcela_proceso', 'comentarios', 'input', 449, 'cumple tamaño maximo', 'SEARCH', 'comentarios_max_size_KO'],
    ['parcela_proceso', 'comentarios', 'input', 450, 'cumple formato', 'SEARCH', 'comentarios_format_KO']
);

let parcela_proceso_tests_fields = Array(
    ['parcela_proceso', 'fecha_aplicacion', 183, 183, 'ADD', [{ fecha_aplicacion: 'ayer' }], 'fecha_aplicacion_format_KO'],
    ['parcela_proceso', 'fecha_aplicacion', 184, 184, 'ADD', [{ fecha_aplicacion: '2026-06-15' }], true],
    ['parcela_proceso', 'fecha_aplicacion', 185, 185, 'EDIT', [{ fecha_aplicacion: 'ayer' }], 'fecha_aplicacion_format_KO'],
    ['parcela_proceso', 'fecha_aplicacion', 186, 186, 'EDIT', [{ fecha_aplicacion: '2026-06-15' }], true],
    ['parcela_proceso', 'descripcion_aplicacion', 187, 187, 'ADD', [{ descripcion_aplicacion: 'D'.repeat(401) }], 'descripcion_aplicacion_max_size_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 188, 188, 'ADD', [{ descripcion_aplicacion: 'Descripcion ok' }], true],
    ['parcela_proceso', 'descripcion_aplicacion', 189, 189, 'EDIT', [{ descripcion_aplicacion: 'D'.repeat(401) }], 'descripcion_aplicacion_max_size_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 190, 190, 'EDIT', [{ descripcion_aplicacion: 'Descripcion ok' }], true],
    ['parcela_proceso', 'comentarios', 191, 191, 'ADD', [{ comentarios: '' }], 'comentarios_min_size_KO'],
    ['parcela_proceso', 'comentarios', 192, 192, 'ADD', [{ comentarios: 'C'.repeat(201) }], 'comentarios_max_size_KO'],
    ['parcela_proceso', 'comentarios', 193, 193, 'ADD', [{ comentarios: '&&&' }], 'comentarios_format_KO'],
    ['parcela_proceso', 'comentarios', 194, 194, 'ADD', [{ comentarios: 'Todo bien' }], true],
    ['parcela_proceso', 'comentarios', 195, 195, 'EDIT', [{ comentarios: '' }], 'comentarios_min_size_KO'],
    ['parcela_proceso', 'comentarios', 196, 196, 'EDIT', [{ comentarios: 'C'.repeat(201) }], 'comentarios_max_size_KO'],
    ['parcela_proceso', 'comentarios', 197, 197, 'EDIT', [{ comentarios: '&&&' }], 'comentarios_format_KO'],
    ['parcela_proceso', 'comentarios', 198, 198, 'EDIT', [{ comentarios: 'Todo bien' }], true],
    ['parcela_proceso', 'fecha_aplicacion', 372, 372, 'SEARCH', [{ fecha_aplicacion: '' }], true],
    ['parcela_proceso', 'descripcion_aplicacion', 373, 373, 'SEARCH', [{ descripcion_aplicacion: '' }], true],
    ['parcela_proceso', 'comentarios', 374, 374, 'SEARCH', [{ comentarios: '' }], true],
    ['parcela_proceso', 'comentarios', 406, 406, 'SEARCH', [{ comentarios: 'Bien' }], true],
    ['parcela_proceso', 'fecha_aplicacion', 445, 445, 'SEARCH', [{ fecha_aplicacion: '1'.repeat(11) }], 'fecha_aplicacion_max_size_KO'],
    ['parcela_proceso', 'fecha_aplicacion', 446, 446, 'SEARCH', [{ fecha_aplicacion: 'abc/def' }], 'fecha_aplicacion_format_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 447, 447, 'SEARCH', [{ descripcion_aplicacion: 'd'.repeat(401) }], 'descripcion_aplicacion_max_size_KO'],
    ['parcela_proceso', 'descripcion_aplicacion', 448, 448, 'SEARCH', [{ descripcion_aplicacion: '<tag>' }], 'descripcion_aplicacion_format_KO'],
    ['parcela_proceso', 'comentarios', 449, 449, 'SEARCH', [{ comentarios: 'c'.repeat(201) }], 'comentarios_max_size_KO'],
    ['parcela_proceso', 'comentarios', 450, 450, 'SEARCH', [{ comentarios: '<tag>' }], 'comentarios_format_KO']
);

let parcela_proceso_tests_files = Array();

let proceso_def_tests = Array(
    ['proceso', 'nombre_proceso', 'input', 199, 'cumple tamaño minimo', 'ADD', 'nombre_proceso_min_size_KO'],
    ['proceso', 'nombre_proceso', 'input', 200, 'cumple tamaño maximo', 'ADD', 'nombre_proceso_max_size_KO'],
    ['proceso', 'nombre_proceso', 'input', 201, 'cumple formato', 'ADD', 'nombre_proceso_format_KO'],
    ['proceso', 'nombre_proceso', 'input', 202, 'es correcto', 'ADD', true],
    ['proceso', 'nombre_proceso', 'input', 203, 'cumple tamaño minimo', 'EDIT', 'nombre_proceso_min_size_KO'],
    ['proceso', 'nombre_proceso', 'input', 204, 'cumple tamaño maximo', 'EDIT', 'nombre_proceso_max_size_KO'],
    ['proceso', 'nombre_proceso', 'input', 205, 'cumple formato', 'EDIT', 'nombre_proceso_format_KO'],
    ['proceso', 'nombre_proceso', 'input', 206, 'es correcto', 'EDIT', true],
    ['proceso', 'descripcion', 'input', 207, 'cumple tamaño minimo', 'ADD', 'descripcion_min_size_KO'],
    ['proceso', 'descripcion', 'input', 208, 'cumple tamaño maximo', 'ADD', 'descripcion_max_size_KO'],
    ['proceso', 'descripcion', 'input', 209, 'cumple formato', 'ADD', 'descripcion_format_KO'],
    ['proceso', 'descripcion', 'input', 210, 'es correcto', 'ADD', true],
    ['proceso', 'descripcion', 'input', 211, 'cumple tamaño minimo', 'EDIT', 'descripcion_min_size_KO'],
    ['proceso', 'descripcion', 'input', 212, 'cumple tamaño maximo', 'EDIT', 'descripcion_max_size_KO'],
    ['proceso', 'descripcion', 'input', 213, 'cumple formato', 'EDIT', 'descripcion_format_KO'],
    ['proceso', 'descripcion', 'input', 214, 'es correcto', 'EDIT', true],
    ['proceso', 'categoria', 'input', 215, 'cumple tamaño minimo', 'ADD', 'categoria_min_size_KO'],
    ['proceso', 'categoria', 'input', 216, 'cumple tamaño maximo', 'ADD', 'categoria_max_size_KO'],
    ['proceso', 'categoria', 'input', 217, 'cumple formato', 'ADD', 'categoria_format_KO'],
    ['proceso', 'categoria', 'input', 218, 'es correcto', 'ADD', true],
    ['proceso', 'categoria', 'input', 219, 'cumple tamaño minimo', 'EDIT', 'categoria_min_size_KO'],
    ['proceso', 'categoria', 'input', 220, 'cumple tamaño maximo', 'EDIT', 'categoria_max_size_KO'],
    ['proceso', 'categoria', 'input', 221, 'cumple formato', 'EDIT', 'categoria_format_KO'],
    ['proceso', 'categoria', 'input', 222, 'es correcto', 'EDIT', true],
    ['proceso', 'archivo_pdf', 'inputfile', 223, 'existe fichero', 'ADD', 'archivo_pdf_not_exist_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 224, 'cumple nombre fichero', 'ADD', 'archivo_pdf_format_name_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 225, 'cumple tipo fichero', 'ADD', 'archivo_pdf_type_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 226, 'cumple tamaño maximo fichero', 'ADD', 'archivo_pdf_max_size_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 227, 'cumple tamaño minimo nombre', 'ADD', 'archivo_pdf_min_size_name_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 228, 'cumple tamaño maximo nombre', 'ADD', 'archivo_pdf_max_size_name_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 229, 'fichero ok', 'ADD', true],
    ['proceso', 'archivo_pdf', 'inputfile', 230, 'no existe fichero', 'EDIT', true],
    ['proceso', 'archivo_pdf', 'inputfile', 231, 'cumple nombre fichero', 'EDIT', 'archivo_pdf_format_name_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 232, 'cumple tipo fichero', 'EDIT', 'archivo_pdf_type_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 233, 'cumple tamaño maximo fichero', 'EDIT', 'archivo_pdf_max_size_file_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 234, 'cumple tamaño minimo nombre', 'EDIT', 'archivo_pdf_min_size_name_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 235, 'cumple tamaño maximo nombre', 'EDIT', 'archivo_pdf_max_size_name_KO'],
    ['proceso', 'archivo_pdf', 'inputfile', 236, 'fichero ok', 'EDIT', true],
    ['proceso', 'url_video', 'input', 237, 'cumple tamaño minimo', 'ADD', 'url_video_min_size_KO'],
    ['proceso', 'url_video', 'input', 238, 'cumple tamaño maximo', 'ADD', 'url_video_max_size_KO'],
    ['proceso', 'url_video', 'input', 239, 'cumple formato', 'ADD', 'url_video_format_KO'],
    ['proceso', 'url_video', 'input', 240, 'es correcto', 'ADD', true],
    ['proceso', 'url_video', 'input', 241, 'cumple tamaño minimo', 'EDIT', 'url_video_min_size_KO'],
    ['proceso', 'url_video', 'input', 242, 'cumple tamaño maximo', 'EDIT', 'url_video_max_size_KO'],
    ['proceso', 'url_video', 'input', 243, 'cumple formato', 'EDIT', 'url_video_format_KO'],
    ['proceso', 'url_video', 'input', 244, 'es correcto', 'EDIT', true],
    ['proceso', 'fecha_aprobacion', 'input', 245, 'cumple formato', 'ADD', 'fecha_aprobacion_format_KO'],
    ['proceso', 'fecha_aprobacion', 'input', 246, 'es correcto', 'ADD', true],
    ['proceso', 'fecha_aprobacion', 'input', 247, 'cumple formato', 'EDIT', 'fecha_aprobacion_format_KO'],
    ['proceso', 'fecha_aprobacion', 'input', 248, 'es correcto', 'EDIT', true],
    ['proceso', 'status', 'select', 249, 'no es correcto', 'ADD', 'status_valor_KO'],
    ['proceso', 'status', 'select', 250, 'es correcto', 'ADD', true],
    ['proceso', 'status', 'select', 251, 'no es correcto', 'EDIT', 'status_valor_KO'],
    ['proceso', 'status', 'select', 252, 'es correcto', 'EDIT', true],
    ['proceso', 'dosis_rec', 'input', 253, 'cumple tamaño minimo', 'ADD', 'dosis_rec_min_size_KO'],
    ['proceso', 'dosis_rec', 'input', 254, 'cumple tamaño maximo', 'ADD', 'dosis_rec_max_size_KO'],
    ['proceso', 'dosis_rec', 'input', 255, 'cumple formato', 'ADD', 'dosis_rec_format_KO'],
    ['proceso', 'dosis_rec', 'input', 256, 'es correcto', 'ADD', true],
    ['proceso', 'dosis_rec', 'input', 257, 'cumple tamaño minimo', 'EDIT', 'dosis_rec_min_size_KO'],
    ['proceso', 'dosis_rec', 'input', 258, 'cumple tamaño maximo', 'EDIT', 'dosis_rec_max_size_KO'],
    ['proceso', 'dosis_rec', 'input', 259, 'cumple formato', 'EDIT', 'dosis_rec_format_KO'],
    ['proceso', 'dosis_rec', 'input', 260, 'es correcto', 'EDIT', true],
    ['proceso', 'nombre_proceso', 'input', 375, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'descripcion', 'input', 376, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'categoria', 'input', 377, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'archivo_pdf', 'inputfile', 378, 'es correcto sin fichero', 'SEARCH', true],
    ['proceso', 'url_video', 'input', 379, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'fecha_aprobacion', 'input', 380, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'status', 'select', 381, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'dosis_rec', 'input', 382, 'es correcto vacío', 'SEARCH', true],
    ['proceso', 'nombre_proceso', 'input', 407, 'es correcto como substring', 'SEARCH', true],
    ['proceso', 'nombre_proceso', 'input', 451, 'cumple tamaño maximo', 'SEARCH', 'nombre_proceso_max_size_KO'],
    ['proceso', 'nombre_proceso', 'input', 452, 'cumple formato', 'SEARCH', 'nombre_proceso_format_KO'],
    ['proceso', 'descripcion', 'input', 453, 'cumple tamaño maximo', 'SEARCH', 'descripcion_max_size_KO'],
    ['proceso', 'descripcion', 'input', 454, 'cumple formato', 'SEARCH', 'descripcion_format_KO'],
    ['proceso', 'url_video', 'input', 455, 'cumple tamaño maximo', 'SEARCH', 'url_video_max_size_KO'],
    ['proceso', 'url_video', 'input', 456, 'cumple formato', 'SEARCH', 'url_video_format_KO'],
    ['proceso', 'fecha_aprobacion', 'input', 457, 'cumple tamaño maximo', 'SEARCH', 'fecha_aprobacion_max_size_KO'],
    ['proceso', 'fecha_aprobacion', 'input', 458, 'cumple formato', 'SEARCH', 'fecha_aprobacion_format_KO'],
    ['proceso', 'dosis_rec', 'input', 459, 'cumple tamaño maximo', 'SEARCH', 'dosis_rec_max_size_KO'],
    ['proceso', 'dosis_rec', 'input', 460, 'cumple formato', 'SEARCH', 'dosis_rec_format_KO']
);

let proceso_tests_fields = Array(
    ['proceso', 'nombre_proceso', 199, 199, 'ADD', [{ nombre_proceso: 'no' }], 'nombre_proceso_min_size_KO'],
    ['proceso', 'nombre_proceso', 200, 200, 'ADD', [{ nombre_proceso: 'N'.repeat(101) }], 'nombre_proceso_max_size_KO'],
    ['proceso', 'nombre_proceso', 201, 201, 'ADD', [{ nombre_proceso: '{}{}' }], 'nombre_proceso_format_KO'],
    ['proceso', 'nombre_proceso', 202, 202, 'ADD', [{ nombre_proceso: 'Proceso 1' }], true],
    ['proceso', 'nombre_proceso', 203, 203, 'EDIT', [{ nombre_proceso: 'no' }], 'nombre_proceso_min_size_KO'],
    ['proceso', 'nombre_proceso', 204, 204, 'EDIT', [{ nombre_proceso: 'N'.repeat(101) }], 'nombre_proceso_max_size_KO'],
    ['proceso', 'nombre_proceso', 205, 205, 'EDIT', [{ nombre_proceso: '{}{}' }], 'nombre_proceso_format_KO'],
    ['proceso', 'nombre_proceso', 206, 206, 'EDIT', [{ nombre_proceso: 'Proceso 1' }], true],
    ['proceso', 'descripcion', 207, 207, 'ADD', [{ descripcion: '' }], 'descripcion_min_size_KO'],
    ['proceso', 'descripcion', 208, 208, 'ADD', [{ descripcion: 'D'.repeat(201) }], 'descripcion_max_size_KO'],
    ['proceso', 'descripcion', 209, 209, 'ADD', [{ descripcion: '___' }], 'descripcion_format_KO'],
    ['proceso', 'descripcion', 210, 210, 'ADD', [{ descripcion: 'Desc proc' }], true],
    ['proceso', 'descripcion', 211, 211, 'EDIT', [{ descripcion: '' }], 'descripcion_min_size_KO'],
    ['proceso', 'descripcion', 212, 212, 'EDIT', [{ descripcion: 'D'.repeat(201) }], 'descripcion_max_size_KO'],
    ['proceso', 'descripcion', 213, 213, 'EDIT', [{ descripcion: '___' }], 'descripcion_format_KO'],
    ['proceso', 'descripcion', 214, 214, 'EDIT', [{ descripcion: 'Desc proc' }], true],
    ['proceso', 'categoria', 215, 215, 'ADD', [{ categoria: 'C' }], 'categoria_min_size_KO'],
    ['proceso', 'categoria', 216, 216, 'ADD', [{ categoria: 'C'.repeat(21) }], 'categoria_max_size_KO'],
    ['proceso', 'categoria', 217, 217, 'ADD', [{ categoria: '???' }], 'categoria_format_KO'],
    ['proceso', 'categoria', 218, 218, 'ADD', [{ categoria: 'Abono' }], true],
    ['proceso', 'categoria', 219, 219, 'EDIT', [{ categoria: 'C' }], 'categoria_min_size_KO'],
    ['proceso', 'categoria', 220, 220, 'EDIT', [{ categoria: 'C'.repeat(21) }], 'categoria_max_size_KO'],
    ['proceso', 'categoria', 221, 221, 'EDIT', [{ categoria: '???' }], 'categoria_format_KO'],
    ['proceso', 'categoria', 222, 222, 'EDIT', [{ categoria: 'Abono' }], true],
    ['proceso', 'url_video', 237, 237, 'ADD', [{ url_video: 'http' }], 'url_video_min_size_KO'],
    ['proceso', 'url_video', 238, 238, 'ADD', [{ url_video: 'U'.repeat(101) }], 'url_video_max_size_KO'],
    ['proceso', 'url_video', 239, 239, 'ADD', [{ url_video: 'no es url' }], 'url_video_format_KO'],
    ['proceso', 'url_video', 240, 240, 'ADD', [{ url_video: 'http://video.com' }], true],
    ['proceso', 'url_video', 241, 241, 'EDIT', [{ url_video: 'http' }], 'url_video_min_size_KO'],
    ['proceso', 'url_video', 242, 242, 'EDIT', [{ url_video: 'U'.repeat(101) }], 'url_video_max_size_KO'],
    ['proceso', 'url_video', 243, 243, 'EDIT', [{ url_video: 'no es url' }], 'url_video_format_KO'],
    ['proceso', 'url_video', 244, 244, 'EDIT', [{ url_video: 'http://video.com' }], true],
    ['proceso', 'fecha_aprobacion', 245, 245, 'ADD', [{ fecha_aprobacion: 'manana' }], 'fecha_aprobacion_format_KO'],
    ['proceso', 'fecha_aprobacion', 246, 246, 'ADD', [{ fecha_aprobacion: '2026-05-01' }], true],
    ['proceso', 'fecha_aprobacion', 247, 247, 'EDIT', [{ fecha_aprobacion: 'manana' }], 'fecha_aprobacion_format_KO'],
    ['proceso', 'fecha_aprobacion', 248, 248, 'EDIT', [{ fecha_aprobacion: '2026-05-01' }], true],
    ['proceso', 'status', 249, 249, 'ADD', [{ status: 'INVALIDO' }], 'status_valor_KO'],
    ['proceso', 'status', 250, 250, 'ADD', [{ status: 'ACTIVO' }], true],
    ['proceso', 'status', 251, 251, 'EDIT', [{ status: 'INVALIDO' }], 'status_valor_KO'],
    ['proceso', 'status', 252, 252, 'EDIT', [{ status: 'ACTIVO' }], true],
    ['proceso', 'dosis_rec', 253, 253, 'ADD', [{ dosis_rec: '' }], 'dosis_rec_min_size_KO'],
    ['proceso', 'dosis_rec', 254, 254, 'ADD', [{ dosis_rec: 'D'.repeat(51) }], 'dosis_rec_max_size_KO'],
    ['proceso', 'dosis_rec', 255, 255, 'ADD', [{ dosis_rec: '$$$' }], 'dosis_rec_format_KO'],
    ['proceso', 'dosis_rec', 256, 256, 'ADD', [{ dosis_rec: 'Dosis 1' }], true],
    ['proceso', 'dosis_rec', 257, 257, 'EDIT', [{ dosis_rec: '' }], 'dosis_rec_min_size_KO'],
    ['proceso', 'dosis_rec', 258, 258, 'EDIT', [{ dosis_rec: 'D'.repeat(51) }], 'dosis_rec_max_size_KO'],
    ['proceso', 'dosis_rec', 259, 259, 'EDIT', [{ dosis_rec: '$$$' }], 'dosis_rec_format_KO'],
    ['proceso', 'dosis_rec', 260, 260, 'EDIT', [{ dosis_rec: 'Dosis 1' }], true],
    ['proceso', 'nombre_proceso', 375, 375, 'SEARCH', [{ nombre_proceso: '' }], true],
    ['proceso', 'descripcion', 376, 376, 'SEARCH', [{ descripcion: '' }], true],
    ['proceso', 'categoria', 377, 377, 'SEARCH', [{ categoria: '' }], true],
    ['proceso', 'url_video', 379, 379, 'SEARCH', [{ url_video: '' }], true],
    ['proceso', 'fecha_aprobacion', 380, 380, 'SEARCH', [{ fecha_aprobacion: '' }], true],
    ['proceso', 'status', 381, 381, 'SEARCH', [{ status: '' }], true],
    ['proceso', 'dosis_rec', 382, 382, 'SEARCH', [{ dosis_rec: '' }], true],
    ['proceso', 'nombre_proceso', 407, 407, 'SEARCH', [{ nombre_proceso: 'Riego' }], true],
    ['proceso', 'nombre_proceso', 451, 451, 'SEARCH', [{ nombre_proceso: 'n'.repeat(101) }], 'nombre_proceso_max_size_KO'],
    ['proceso', 'nombre_proceso', 452, 452, 'SEARCH', [{ nombre_proceso: '###' }], 'nombre_proceso_format_KO'],
    ['proceso', 'descripcion', 453, 453, 'SEARCH', [{ descripcion: 'd'.repeat(501) }], 'descripcion_max_size_KO'],
    ['proceso', 'descripcion', 454, 454, 'SEARCH', [{ descripcion: '<tag>' }], 'descripcion_format_KO'],
    ['proceso', 'url_video', 455, 455, 'SEARCH', [{ url_video: 'u'.repeat(101) }], 'url_video_max_size_KO'],
    ['proceso', 'url_video', 456, 456, 'SEARCH', [{ url_video: '###url' }], 'url_video_format_KO'],
    ['proceso', 'fecha_aprobacion', 457, 457, 'SEARCH', [{ fecha_aprobacion: '1'.repeat(11) }], 'fecha_aprobacion_max_size_KO'],
    ['proceso', 'fecha_aprobacion', 458, 458, 'SEARCH', [{ fecha_aprobacion: 'abc/def' }], 'fecha_aprobacion_format_KO'],
    ['proceso', 'dosis_rec', 459, 459, 'SEARCH', [{ dosis_rec: 'd'.repeat(51) }], 'dosis_rec_max_size_KO'],
    ['proceso', 'dosis_rec', 460, 460, 'SEARCH', [{ dosis_rec: '<tag>' }], 'dosis_rec_format_KO']
);

let proceso_tests_files = Array(
    ['proceso', 'archivo_pdf', 223, 223, 'ADD', 'existe', [], 'archivo_pdf_not_exist_file_KO'],
    ['proceso', 'archivo_pdf', 224, 224, 'ADD', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'archivo_pdf_format_name_file_KO'],
    ['proceso', 'archivo_pdf', 225, 225, 'ADD', 'type_file', [{ format_name_file: 'doc.pdf' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'archivo_pdf_type_file_KO'],
    ['proceso', 'archivo_pdf', 226, 226, 'ADD', 'max_size_file', [{ format_name_file: 'doc.pdf' }, { type_file: 'application/pdf' }, { max_size_file: 15000000 }], 'archivo_pdf_max_size_file_KO'],
    ['proceso', 'archivo_pdf', 227, 227, 'ADD', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'archivo_pdf_min_size_name_KO'],
    ['proceso', 'archivo_pdf', 228, 228, 'ADD', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'archivo_pdf_max_size_name_KO'],
    ['proceso', 'archivo_pdf', 229, 229, 'ADD', 'fichero ok', [{ format_name_file: 'doc.pdf' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], true],
    ['proceso', 'archivo_pdf', 230, 230, 'EDIT', 'noexiste', [], true],
    ['proceso', 'archivo_pdf', 231, 231, 'EDIT', 'format_name_file', [{ format_name_file: '111!!' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'archivo_pdf_format_name_file_KO'],
    ['proceso', 'archivo_pdf', 232, 232, 'EDIT', 'type_file', [{ format_name_file: 'doc.pdf' }, { type_file: 'image/jpeg' }, { max_size_file: 5000 }], 'archivo_pdf_type_file_KO'],
    ['proceso', 'archivo_pdf', 233, 233, 'EDIT', 'max_size_file', [{ format_name_file: 'doc.pdf' }, { type_file: 'application/pdf' }, { max_size_file: 15000000 }], 'archivo_pdf_max_size_file_KO'],
    ['proceso', 'archivo_pdf', 234, 234, 'EDIT', 'min_size_name', [{ format_name_file: 'a' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'archivo_pdf_min_size_name_KO'],
    ['proceso', 'archivo_pdf', 235, 235, 'EDIT', 'max_size_name', [{ format_name_file: 'a'.repeat(200) }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], 'archivo_pdf_max_size_name_KO'],
    ['proceso', 'archivo_pdf', 236, 236, 'EDIT', 'fichero ok', [{ format_name_file: 'doc.pdf' }, { type_file: 'application/pdf' }, { max_size_file: 5000 }], true],
    ['proceso', 'archivo_pdf', 378, 378, 'SEARCH', 'noexiste', [], true]
);

let user_def_tests = Array(
    ['usuario', 'usuario_login', 'input', 261, 'cumple tamaño minimo', 'ADD', 'usuario_login_min_size_KO'],
    ['usuario', 'usuario_login', 'input', 262, 'cumple tamaño maximo', 'ADD', 'usuario_login_max_size_KO'],
    ['usuario', 'usuario_login', 'input', 263, 'cumple formato', 'ADD', 'usuario_login_format_KO'],
    ['usuario', 'usuario_login', 'input', 264, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_login', 'input', 265, 'cumple tamaño minimo', 'EDIT', 'usuario_login_min_size_KO'],
    ['usuario', 'usuario_login', 'input', 266, 'cumple tamaño maximo', 'EDIT', 'usuario_login_max_size_KO'],
    ['usuario', 'usuario_login', 'input', 267, 'cumple formato', 'EDIT', 'usuario_login_format_KO'],
    ['usuario', 'usuario_login', 'input', 268, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_password', 'input', 269, 'cumple tamaño minimo', 'ADD', 'usuario_password_min_size_KO'],
    ['usuario', 'usuario_password', 'input', 270, 'cumple tamaño maximo', 'ADD', 'usuario_password_max_size_KO'],
    ['usuario', 'usuario_password', 'input', 271, 'cumple formato', 'ADD', 'usuario_password_format_KO'],
    ['usuario', 'usuario_password', 'input', 272, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_password', 'input', 273, 'cumple tamaño minimo', 'EDIT', 'usuario_password_min_size_KO'],
    ['usuario', 'usuario_password', 'input', 274, 'cumple tamaño maximo', 'EDIT', 'usuario_password_max_size_KO'],
    ['usuario', 'usuario_password', 'input', 275, 'cumple formato', 'EDIT', 'usuario_password_format_KO'],
    ['usuario', 'usuario_password', 'input', 276, 'es correcto', 'EDIT', true],
    ['usuario', 'identificacion_nacional', 'input', 277, 'cumple tamaño minimo', 'ADD', 'identificacion_nacional_min_size_KO'],
    ['usuario', 'identificacion_nacional', 'input', 278, 'cumple tamaño maximo', 'ADD', 'identificacion_nacional_max_size_KO'],
    ['usuario', 'identificacion_nacional', 'input', 279, 'cumple formato', 'ADD', 'identificacion_nacional_format_KO'],
    ['usuario', 'identificacion_nacional', 'input', 280, 'es correcto', 'ADD', true],
    ['usuario', 'identificacion_nacional', 'input', 281, 'cumple tamaño minimo', 'EDIT', 'identificacion_nacional_min_size_KO'],
    ['usuario', 'identificacion_nacional', 'input', 282, 'cumple tamaño maximo', 'EDIT', 'identificacion_nacional_max_size_KO'],
    ['usuario', 'identificacion_nacional', 'input', 283, 'cumple formato', 'EDIT', 'identificacion_nacional_format_KO'],
    ['usuario', 'identificacion_nacional', 'input', 284, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_nombre', 'input', 285, 'cumple tamaño minimo', 'ADD', 'usuario_nombre_min_size_KO'],
    ['usuario', 'usuario_nombre', 'input', 286, 'cumple tamaño maximo', 'ADD', 'usuario_nombre_max_size_KO'],
    ['usuario', 'usuario_nombre', 'input', 287, 'cumple formato', 'ADD', 'usuario_nombre_format_KO'],
    ['usuario', 'usuario_nombre', 'input', 288, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_nombre', 'input', 289, 'cumple tamaño minimo', 'EDIT', 'usuario_nombre_min_size_KO'],
    ['usuario', 'usuario_nombre', 'input', 290, 'cumple tamaño maximo', 'EDIT', 'usuario_nombre_max_size_KO'],
    ['usuario', 'usuario_nombre', 'input', 291, 'cumple formato', 'EDIT', 'usuario_nombre_format_KO'],
    ['usuario', 'usuario_nombre', 'input', 292, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_apellidos', 'input', 293, 'cumple tamaño minimo', 'ADD', 'usuario_apellidos_min_size_KO'],
    ['usuario', 'usuario_apellidos', 'input', 294, 'cumple tamaño maximo', 'ADD', 'usuario_apellidos_max_size_KO'],
    ['usuario', 'usuario_apellidos', 'input', 295, 'cumple formato', 'ADD', 'usuario_apellidos_format_KO'],
    ['usuario', 'usuario_apellidos', 'input', 296, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_apellidos', 'input', 297, 'cumple tamaño minimo', 'EDIT', 'usuario_apellidos_min_size_KO'],
    ['usuario', 'usuario_apellidos', 'input', 298, 'cumple tamaño maximo', 'EDIT', 'usuario_apellidos_max_size_KO'],
    ['usuario', 'usuario_apellidos', 'input', 299, 'cumple formato', 'EDIT', 'usuario_apellidos_format_KO'],
    ['usuario', 'usuario_apellidos', 'input', 300, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_telefono', 'input', 301, 'cumple tamaño minimo', 'ADD', 'usuario_telefono_min_size_KO'],
    ['usuario', 'usuario_telefono', 'input', 302, 'cumple tamaño maximo', 'ADD', 'usuario_telefono_max_size_KO'],
    ['usuario', 'usuario_telefono', 'input', 303, 'cumple formato', 'ADD', 'usuario_telefono_format_KO'],
    ['usuario', 'usuario_telefono', 'input', 304, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_telefono', 'input', 305, 'cumple tamaño minimo', 'EDIT', 'usuario_telefono_min_size_KO'],
    ['usuario', 'usuario_telefono', 'input', 306, 'cumple tamaño maximo', 'EDIT', 'usuario_telefono_max_size_KO'],
    ['usuario', 'usuario_telefono', 'input', 307, 'cumple formato', 'EDIT', 'usuario_telefono_format_KO'],
    ['usuario', 'usuario_telefono', 'input', 308, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_email', 'input', 309, 'cumple tamaño minimo', 'ADD', 'usuario_email_min_size_KO'],
    ['usuario', 'usuario_email', 'input', 310, 'cumple tamaño maximo', 'ADD', 'usuario_email_max_size_KO'],
    ['usuario', 'usuario_email', 'input', 311, 'cumple formato', 'ADD', 'usuario_email_format_KO'],
    ['usuario', 'usuario_email', 'input', 312, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_email', 'input', 313, 'cumple tamaño minimo', 'EDIT', 'usuario_email_min_size_KO'],
    ['usuario', 'usuario_email', 'input', 314, 'cumple tamaño maximo', 'EDIT', 'usuario_email_max_size_KO'],
    ['usuario', 'usuario_email', 'input', 315, 'cumple formato', 'EDIT', 'usuario_email_format_KO'],
    ['usuario', 'usuario_email', 'input', 316, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_direccion', 'input', 317, 'cumple tamaño minimo', 'ADD', 'usuario_direccion_min_size_KO'],
    ['usuario', 'usuario_direccion', 'input', 318, 'cumple tamaño maximo', 'ADD', 'usuario_direccion_max_size_KO'],
    ['usuario', 'usuario_direccion', 'input', 319, 'cumple formato', 'ADD', 'usuario_direccion_format_KO'],
    ['usuario', 'usuario_direccion', 'input', 320, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_direccion', 'input', 321, 'cumple tamaño minimo', 'EDIT', 'usuario_direccion_min_size_KO'],
    ['usuario', 'usuario_direccion', 'input', 322, 'cumple tamaño maximo', 'EDIT', 'usuario_direccion_max_size_KO'],
    ['usuario', 'usuario_direccion', 'input', 323, 'cumple formato', 'EDIT', 'usuario_direccion_format_KO'],
    ['usuario', 'usuario_direccion', 'input', 324, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_fechaNacimiento', 'input', 325, 'cumple formato', 'ADD', 'usuario_fechaNacimiento_format_KO'],
    ['usuario', 'usuario_fechaNacimiento', 'input', 326, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_fechaNacimiento', 'input', 327, 'cumple formato', 'EDIT', 'usuario_fechaNacimiento_format_KO'],
    ['usuario', 'usuario_fechaNacimiento', 'input', 328, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_pais', 'input', 329, 'cumple tamaño minimo', 'ADD', 'usuario_pais_min_size_KO'],
    ['usuario', 'usuario_pais', 'input', 330, 'cumple tamaño maximo', 'ADD', 'usuario_pais_max_size_KO'],
    ['usuario', 'usuario_pais', 'input', 331, 'cumple formato', 'ADD', 'usuario_pais_format_KO'],
    ['usuario', 'usuario_pais', 'input', 332, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_pais', 'input', 333, 'cumple tamaño minimo', 'EDIT', 'usuario_pais_min_size_KO'],
    ['usuario', 'usuario_pais', 'input', 334, 'cumple tamaño maximo', 'EDIT', 'usuario_pais_max_size_KO'],
    ['usuario', 'usuario_pais', 'input', 335, 'cumple formato', 'EDIT', 'usuario_pais_format_KO'],
    ['usuario', 'usuario_pais', 'input', 336, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_genero', 'select', 337, 'no es correcto', 'ADD', 'usuario_genero_valor_KO'],
    ['usuario', 'usuario_genero', 'select', 338, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_genero', 'select', 339, 'no es correcto', 'EDIT', 'usuario_genero_valor_KO'],
    ['usuario', 'usuario_genero', 'select', 340, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_estudios', 'select', 341, 'no es correcto', 'ADD', 'usuario_estudios_valor_KO'],
    ['usuario', 'usuario_estudios', 'select', 342, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_estudios', 'select', 343, 'no es correcto', 'EDIT', 'usuario_estudios_valor_KO'],
    ['usuario', 'usuario_estudios', 'select', 344, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_rol', 'select', 345, 'no es correcto', 'ADD', 'usuario_rol_valor_KO'],
    ['usuario', 'usuario_rol', 'select', 346, 'es correcto', 'ADD', true],
    ['usuario', 'usuario_rol', 'select', 347, 'no es correcto', 'EDIT', 'usuario_rol_valor_KO'],
    ['usuario', 'usuario_rol', 'select', 348, 'es correcto', 'EDIT', true],
    ['usuario', 'usuario_nombre', 'input', 383, 'cumple formato', 'SEARCH', 'usuario_nombre_format_KO'],
    ['usuario', 'usuario_nombre', 'input', 384, 'es correcto', 'SEARCH', true],
    ['usuario', 'usuario_apellidos', 'input', 385, 'cumple formato', 'SEARCH', 'usuario_apellidos_format_KO'],
    ['usuario', 'usuario_apellidos', 'input', 386, 'es correcto', 'SEARCH', true],
    ['usuario', 'identificacion_nacional', 'input', 387, 'cumple formato', 'SEARCH', 'identificacion_nacional_format_KO'],
    ['usuario', 'identificacion_nacional', 'input', 388, 'es correcto', 'SEARCH', true],
    ['usuario', 'usuario_telefono', 'input', 389, 'cumple formato', 'SEARCH', 'usuario_telefono_format_KO'],
    ['usuario', 'usuario_telefono', 'input', 390, 'es correcto', 'SEARCH', true],
    ['usuario', 'usuario_fechaNacimiento', 'input', 391, 'cumple formato', 'SEARCH', 'usuario_fechaNacimiento_format_KO'],
    ['usuario', 'usuario_fechaNacimiento', 'input', 392, 'es correcto', 'SEARCH', true],
    ['usuario', 'usuario_direccion', 'input', 393, 'cumple formato', 'SEARCH', 'usuario_direccion_format_KO'],
    ['usuario', 'usuario_direccion', 'input', 394, 'es correcto', 'SEARCH', true],
    ['usuario', 'usuario_login', 'input', 395, 'cumple formato', 'SEARCH', 'usuario_login_format_KO'],
    ['usuario', 'usuario_login', 'input', 396, 'es correcto', 'SEARCH', true],
    ['usuario', 'usuario_estudios', 'select', 397, 'es correcto vacío', 'SEARCH', true],
    ['usuario', 'usuario_genero', 'select', 398, 'es correcto vacío', 'SEARCH', true],
    ['usuario', 'usuario_pais', 'input', 399, 'es correcto vacío', 'SEARCH', true],
    ['usuario', 'usuario_rol', 'select', 400, 'es correcto vacío', 'SEARCH', true],
    ['usuario', 'usuario_password', 'input', 401, 'es correcto vacío', 'SEARCH', true],
    ['usuario', 'identificacion_nacional', 'input', 408, 'es correcto como substring parcial', 'SEARCH', true],
    ['usuario', 'usuario_nombre', 'input', 461, 'cumple tamaño maximo', 'SEARCH', 'usuario_nombre_max_size_KO'],
    ['usuario', 'usuario_apellidos', 'input', 462, 'cumple tamaño maximo', 'SEARCH', 'usuario_apellidos_max_size_KO'],
    ['usuario', 'identificacion_nacional', 'input', 463, 'cumple tamaño maximo', 'SEARCH', 'identificacion_nacional_max_size_KO'],
    ['usuario', 'usuario_telefono', 'input', 464, 'cumple tamaño maximo', 'SEARCH', 'usuario_telefono_max_size_KO'],
    ['usuario', 'usuario_fechaNacimiento', 'input', 465, 'cumple tamaño maximo', 'SEARCH', 'usuario_fechaNacimiento_max_size_KO'],
    ['usuario', 'usuario_direccion', 'input', 466, 'cumple tamaño maximo', 'SEARCH', 'usuario_direccion_max_size_KO'],
    ['usuario', 'usuario_login', 'input', 467, 'cumple tamaño maximo', 'SEARCH', 'usuario_login_max_size_KO']
);

let user_tests_fields = Array(
    ['usuario', 'usuario_login', 261, 261, 'ADD', [{ usuario_login: 'lo' }], 'usuario_login_min_size_KO'],
    ['usuario', 'usuario_login', 262, 262, 'ADD', [{ usuario_login: 'L'.repeat(31) }], 'usuario_login_max_size_KO'],
    ['usuario', 'usuario_login', 263, 263, 'ADD', [{ usuario_login: '$$$' }], 'usuario_login_format_KO'],
    ['usuario', 'usuario_login', 264, 264, 'ADD', [{ usuario_login: 'pepito' }], true],
    ['usuario', 'usuario_login', 265, 265, 'EDIT', [{ usuario_login: 'lo' }], 'usuario_login_min_size_KO'],
    ['usuario', 'usuario_login', 266, 266, 'EDIT', [{ usuario_login: 'L'.repeat(31) }], 'usuario_login_max_size_KO'],
    ['usuario', 'usuario_login', 267, 267, 'EDIT', [{ usuario_login: '$$$' }], 'usuario_login_format_KO'],
    ['usuario', 'usuario_login', 268, 268, 'EDIT', [{ usuario_login: 'pepito' }], true],
    ['usuario', 'usuario_password', 269, 269, 'ADD', [{ usuario_password: 'pa' }], 'usuario_password_min_size_KO'],
    ['usuario', 'usuario_password', 270, 270, 'ADD', [{ usuario_password: 'P'.repeat(101) }], 'usuario_password_max_size_KO'],
    ['usuario', 'usuario_password', 271, 271, 'ADD', [{ usuario_password: '!!!' }], 'usuario_password_format_KO'],
    ['usuario', 'usuario_password', 272, 272, 'ADD', [{ usuario_password: 'Pepe123!' }], true],
    ['usuario', 'usuario_password', 273, 273, 'EDIT', [{ usuario_password: 'pa' }], 'usuario_password_min_size_KO'],
    ['usuario', 'usuario_password', 274, 274, 'EDIT', [{ usuario_password: 'P'.repeat(101) }], 'usuario_password_max_size_KO'],
    ['usuario', 'usuario_password', 275, 275, 'EDIT', [{ usuario_password: '!!!' }], 'usuario_password_format_KO'],
    ['usuario', 'usuario_password', 276, 276, 'EDIT', [{ usuario_password: 'Pepe123!' }], true],
    ['usuario', 'identificacion_nacional', 277, 277, 'ADD', [{ identificacion_nacional: '1234' }], 'identificacion_nacional_min_size_KO'],
    ['usuario', 'identificacion_nacional', 278, 278, 'ADD', [{ identificacion_nacional: 'I'.repeat(21) }], 'identificacion_nacional_max_size_KO'],
    ['usuario', 'identificacion_nacional', 279, 279, 'ADD', [{ identificacion_nacional: '123???' }], 'identificacion_nacional_format_KO'],
    ['usuario', 'identificacion_nacional', 280, 280, 'ADD', [{ identificacion_nacional: '12345678Z' }], true],
    ['usuario', 'identificacion_nacional', 281, 281, 'EDIT', [{ identificacion_nacional: '1234' }], 'identificacion_nacional_min_size_KO'],
    ['usuario', 'identificacion_nacional', 282, 282, 'EDIT', [{ identificacion_nacional: 'I'.repeat(21) }], 'identificacion_nacional_max_size_KO'],
    ['usuario', 'identificacion_nacional', 283, 283, 'EDIT', [{ identificacion_nacional: '2342***' }], 'identificacion_nacional_format_KO'],
    ['usuario', 'identificacion_nacional', 284, 284, 'EDIT', [{ identificacion_nacional: '12345678Z' }], true],
    ['usuario', 'usuario_nombre', 285, 285, 'ADD', [{ usuario_nombre: 'n' }], 'usuario_nombre_min_size_KO'],
    ['usuario', 'usuario_nombre', 286, 286, 'ADD', [{ usuario_nombre: 'N'.repeat(36) }], 'usuario_nombre_max_size_KO'],
    ['usuario', 'usuario_nombre', 287, 287, 'ADD', [{ usuario_nombre: '123' }], 'usuario_nombre_format_KO'],
    ['usuario', 'usuario_nombre', 288, 288, 'ADD', [{ usuario_nombre: 'Juan' }], true],
    ['usuario', 'usuario_nombre', 289, 289, 'EDIT', [{ usuario_nombre: 'n' }], 'usuario_nombre_min_size_KO'],
    ['usuario', 'usuario_nombre', 290, 290, 'EDIT', [{ usuario_nombre: 'N'.repeat(36) }], 'usuario_nombre_max_size_KO'],
    ['usuario', 'usuario_nombre', 291, 291, 'EDIT', [{ usuario_nombre: '123' }], 'usuario_nombre_format_KO'],
    ['usuario', 'usuario_nombre', 292, 292, 'EDIT', [{ usuario_nombre: 'Juan' }], true],
    ['usuario', 'usuario_apellidos', 293, 293, 'ADD', [{ usuario_apellidos: 'a' }], 'usuario_apellidos_min_size_KO'],
    ['usuario', 'usuario_apellidos', 294, 294, 'ADD', [{ usuario_apellidos: 'A'.repeat(51) }], 'usuario_apellidos_max_size_KO'],
    ['usuario', 'usuario_apellidos', 295, 295, 'ADD', [{ usuario_apellidos: '123' }], 'usuario_apellidos_format_KO'],
    ['usuario', 'usuario_apellidos', 296, 296, 'ADD', [{ usuario_apellidos: 'Perez' }], true],
    ['usuario', 'usuario_apellidos', 297, 297, 'EDIT', [{ usuario_apellidos: 'a' }], 'usuario_apellidos_min_size_KO'],
    ['usuario', 'usuario_apellidos', 298, 298, 'EDIT', [{ usuario_apellidos: 'A'.repeat(51) }], 'usuario_apellidos_max_size_KO'],
    ['usuario', 'usuario_apellidos', 299, 299, 'EDIT', [{ usuario_apellidos: '123' }], 'usuario_apellidos_format_KO'],
    ['usuario', 'usuario_apellidos', 300, 300, 'EDIT', [{ usuario_apellidos: 'Perez' }], true],
    ['usuario', 'usuario_telefono', 301, 301, 'ADD', [{ usuario_telefono: '1234' }], 'usuario_telefono_min_size_KO'],
    ['usuario', 'usuario_telefono', 302, 302, 'ADD', [{ usuario_telefono: 'T'.repeat(16) }], 'usuario_telefono_max_size_KO'],
    ['usuario', 'usuario_telefono', 303, 303, 'ADD', [{ usuario_telefono: 'letras' }], 'usuario_telefono_format_KO'],
    ['usuario', 'usuario_telefono', 304, 304, 'ADD', [{ usuario_telefono: '600123456' }], true],
    ['usuario', 'usuario_telefono', 305, 305, 'EDIT', [{ usuario_telefono: '1234' }], 'usuario_telefono_min_size_KO'],
    ['usuario', 'usuario_telefono', 306, 306, 'EDIT', [{ usuario_telefono: 'T'.repeat(16) }], 'usuario_telefono_max_size_KO'],
    ['usuario', 'usuario_telefono', 307, 307, 'EDIT', [{ usuario_telefono: 'letras' }], 'usuario_telefono_format_KO'],
    ['usuario', 'usuario_telefono', 308, 308, 'EDIT', [{ usuario_telefono: '600123456' }], true],
    ['usuario', 'usuario_email', 309, 309, 'ADD', [{ usuario_email: 'a@b' }], 'usuario_email_min_size_KO'],
    ['usuario', 'usuario_email', 310, 310, 'ADD', [{ usuario_email: 'E'.repeat(61) }], 'usuario_email_max_size_KO'],
    ['usuario', 'usuario_email', 311, 311, 'ADD', [{ usuario_email: 'noescorreo' }], 'usuario_email_format_KO'],
    ['usuario', 'usuario_email', 312, 312, 'ADD', [{ usuario_email: 'a@b.com' }], true],
    ['usuario', 'usuario_email', 313, 313, 'EDIT', [{ usuario_email: 'a@b' }], 'usuario_email_min_size_KO'],
    ['usuario', 'usuario_email', 314, 314, 'EDIT', [{ usuario_email: 'E'.repeat(61) }], 'usuario_email_max_size_KO'],
    ['usuario', 'usuario_email', 315, 315, 'EDIT', [{ usuario_email: 'noescorreo' }], 'usuario_email_format_KO'],
    ['usuario', 'usuario_email', 316, 316, 'EDIT', [{ usuario_email: 'a@b.com' }], true],
    ['usuario', 'usuario_direccion', 317, 317, 'ADD', [{ usuario_direccion: 'dir' }], 'usuario_direccion_min_size_KO'],
    ['usuario', 'usuario_direccion', 318, 318, 'ADD', [{ usuario_direccion: 'D'.repeat(151) }], 'usuario_direccion_max_size_KO'],
    ['usuario', 'usuario_direccion', 319, 319, 'ADD', [{ usuario_direccion: '{{{{{' }], 'usuario_direccion_format_KO'],
    ['usuario', 'usuario_direccion', 320, 320, 'ADD', [{ usuario_direccion: 'Calle Falsa 123' }], true],
    ['usuario', 'usuario_direccion', 321, 321, 'EDIT', [{ usuario_direccion: 'dir' }], 'usuario_direccion_min_size_KO'],
    ['usuario', 'usuario_direccion', 322, 322, 'EDIT', [{ usuario_direccion: 'D'.repeat(151) }], 'usuario_direccion_max_size_KO'],
    ['usuario', 'usuario_direccion', 323, 323, 'EDIT', [{ usuario_direccion: '{{{{{' }], 'usuario_direccion_format_KO'],
    ['usuario', 'usuario_direccion', 324, 324, 'EDIT', [{ usuario_direccion: 'Calle Falsa 123' }], true],
    ['usuario', 'usuario_fechaNacimiento', 325, 325, 'ADD', [{ usuario_fechaNacimiento: '88-99-00' }], 'usuario_fechaNacimiento_format_KO'],
    ['usuario', 'usuario_fechaNacimiento', 326, 326, 'ADD', [{ usuario_fechaNacimiento: '1990-01-01' }], true],
    ['usuario', 'usuario_fechaNacimiento', 327, 327, 'EDIT', [{ usuario_fechaNacimiento: '88-99-00' }], 'usuario_fechaNacimiento_format_KO'],
    ['usuario', 'usuario_fechaNacimiento', 328, 328, 'EDIT', [{ usuario_fechaNacimiento: '1990-01-01' }], true],
    ['usuario', 'usuario_pais', 329, 329, 'ADD', [{ usuario_pais: 'P' }], 'usuario_pais_min_size_KO'],
    ['usuario', 'usuario_pais', 330, 330, 'ADD', [{ usuario_pais: 'P'.repeat(41) }], 'usuario_pais_max_size_KO'],
    ['usuario', 'usuario_pais', 331, 331, 'ADD', [{ usuario_pais: '123' }], 'usuario_pais_format_KO'],
    ['usuario', 'usuario_pais', 332, 332, 'ADD', [{ usuario_pais: 'Espana' }], true],
    ['usuario', 'usuario_pais', 333, 333, 'EDIT', [{ usuario_pais: 'P' }], 'usuario_pais_min_size_KO'],
    ['usuario', 'usuario_pais', 334, 334, 'EDIT', [{ usuario_pais: 'P'.repeat(41) }], 'usuario_pais_max_size_KO'],
    ['usuario', 'usuario_pais', 335, 335, 'EDIT', [{ usuario_pais: '123' }], 'usuario_pais_format_KO'],
    ['usuario', 'usuario_pais', 336, 336, 'EDIT', [{ usuario_pais: 'Espana' }], true],
    ['usuario', 'usuario_genero', 337, 337, 'ADD', [{ usuario_genero: 'Ninguno' }], 'usuario_genero_valor_KO'],
    ['usuario', 'usuario_genero', 338, 338, 'ADD', [{ usuario_genero: 'MASCULINO' }], true],
    ['usuario', 'usuario_genero', 339, 339, 'EDIT', [{ usuario_genero: 'Ninguno' }], 'usuario_genero_valor_KO'],
    ['usuario', 'usuario_genero', 340, 340, 'EDIT', [{ usuario_genero: 'MASCULINO' }], true],
    ['usuario', 'usuario_estudios', 341, 341, 'ADD', [{ usuario_estudios: 'Ninguno' }], 'usuario_estudios_valor_KO'],
    ['usuario', 'usuario_estudios', 342, 342, 'ADD', [{ usuario_estudios: 'PRIMARIA' }], true],
    ['usuario', 'usuario_estudios', 343, 343, 'EDIT', [{ usuario_estudios: 'Ninguno' }], 'usuario_estudios_valor_KO'],
    ['usuario', 'usuario_estudios', 344, 344, 'EDIT', [{ usuario_estudios: 'PRIMARIA' }], true],
    ['usuario', 'usuario_rol', 345, 345, 'ADD', [{ usuario_rol: 'Ninguno' }], 'usuario_rol_valor_KO'],
    ['usuario', 'usuario_rol', 346, 346, 'ADD', [{ usuario_rol: 'USUARIO' }], true],
    ['usuario', 'usuario_rol', 347, 347, 'EDIT', [{ usuario_rol: 'Ninguno' }], 'usuario_rol_valor_KO'],
    ['usuario', 'usuario_rol', 348, 348, 'EDIT', [{ usuario_rol: 'USUARIO' }], true],
    ['usuario', 'usuario_nombre', 383, 383, 'SEARCH', [{ usuario_nombre: '123' }], 'usuario_nombre_format_KO'],
    ['usuario', 'usuario_nombre', 384, 384, 'SEARCH', [{ usuario_nombre: 'Juan' }], true],
    ['usuario', 'usuario_apellidos', 385, 385, 'SEARCH', [{ usuario_apellidos: '123' }], 'usuario_apellidos_format_KO'],
    ['usuario', 'usuario_apellidos', 386, 386, 'SEARCH', [{ usuario_apellidos: 'Perez' }], true],
    ['usuario', 'identificacion_nacional', 387, 387, 'SEARCH', [{ identificacion_nacional: 'invalid' }], 'identificacion_nacional_format_KO'],
    ['usuario', 'identificacion_nacional', 388, 388, 'SEARCH', [{ identificacion_nacional: '12345678Z' }], true],
    ['usuario', 'usuario_telefono', 389, 389, 'SEARCH', [{ usuario_telefono: 'telefono' }], 'usuario_telefono_format_KO'],
    ['usuario', 'usuario_telefono', 390, 390, 'SEARCH', [{ usuario_telefono: '' }], true],
    ['usuario', 'usuario_fechaNacimiento', 391, 391, 'SEARCH', [{ usuario_fechaNacimiento: '31/12/2000' }], 'usuario_fechaNacimiento_format_KO'],
    ['usuario', 'usuario_fechaNacimiento', 392, 392, 'SEARCH', [{ usuario_fechaNacimiento: '2000-01-01' }], true],
    ['usuario', 'usuario_direccion', 393, 393, 'SEARCH', [{ usuario_direccion: '{{{{{' }], 'usuario_direccion_format_KO'],
    ['usuario', 'usuario_direccion', 394, 394, 'SEARCH', [{ usuario_direccion: 'Calle Falsa' }], true],
    ['usuario', 'usuario_login', 395, 395, 'SEARCH', [{ usuario_login: '##login' }], 'usuario_login_format_KO'],
    ['usuario', 'usuario_login', 396, 396, 'SEARCH', [{ usuario_login: 'pepito' }], true],
    ['usuario', 'usuario_estudios', 397, 397, 'SEARCH', [{ usuario_estudios: '' }], true],
    ['usuario', 'usuario_genero', 398, 398, 'SEARCH', [{ usuario_genero: '' }], true],
    ['usuario', 'usuario_pais', 399, 399, 'SEARCH', [{ usuario_pais: '' }], true],
    ['usuario', 'usuario_rol', 400, 400, 'SEARCH', [{ usuario_rol: '' }], true],
    ['usuario', 'usuario_password', 401, 401, 'SEARCH', [{ usuario_password: '' }], true],
    ['usuario', 'identificacion_nacional', 408, 408, 'SEARCH', [{ identificacion_nacional: '1234' }], true],
    ['usuario', 'usuario_nombre', 461, 461, 'SEARCH', [{ usuario_nombre: 'n'.repeat(36) }], 'usuario_nombre_max_size_KO'],
    ['usuario', 'usuario_apellidos', 462, 462, 'SEARCH', [{ usuario_apellidos: 'a'.repeat(51) }], 'usuario_apellidos_max_size_KO'],
    ['usuario', 'identificacion_nacional', 463, 463, 'SEARCH', [{ identificacion_nacional: '1'.repeat(10) }], 'identificacion_nacional_max_size_KO'],
    ['usuario', 'usuario_telefono', 464, 464, 'SEARCH', [{ usuario_telefono: '1'.repeat(16) }], 'usuario_telefono_max_size_KO'],
    ['usuario', 'usuario_fechaNacimiento', 465, 465, 'SEARCH', [{ usuario_fechaNacimiento: '1'.repeat(11) }], 'usuario_fechaNacimiento_max_size_KO'],
    ['usuario', 'usuario_direccion', 466, 466, 'SEARCH', [{ usuario_direccion: 'a'.repeat(151) }], 'usuario_direccion_max_size_KO'],
    ['usuario', 'usuario_login', 467, 467, 'SEARCH', [{ usuario_login: 'l'.repeat(31) }], 'usuario_login_max_size_KO']
);

let user_tests_files = Array();

